### ISSUE TITLE
metaImport needs a -n option

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal#1455] opened 2016-07-06 11:52 UTC
Discussed with @pieterlukasse and thought about this some more last night.

I think the metaImport script needs a -n (--no_portal_checks) option.  This option already exists in validateData.py, we just need to pass it along.

That way a new user who is following the installation steps on the wiki can successfully import data without having a portal instance already running.  This is important because in the wiki docs, we suggest that people get the entire database set up first, and then deploy the web app.  Without a -n option, new installs are blocked from importing data.

@pieterlukasse suggested that we use cbioportalImporter.py, which provides this functionality.  But, I would much rather introduce the right scripts up-front, e.g. introduce others to the validator and metaImport, so that they can see how it works up-front.

Since @priti88 is out, I will endeavor to try to fix on my own today.  Otherwise, may call upon @ersinciftci.

**Comment by fedde-s** [comment] 2016-07-06 12:49
This was left out by design, as studies should be fully validated (including whether the genes are known to the portal, for instance) before importing. There’s a `-p`/`--portal_info_dir` option in case no web API is accessible: https://github.com/cBioPortal/cbioportal/blob/master/docs/Using-the-dataset-validator.md#offline-validation

**Comment by fedde-s** [comment] 2016-07-06 12:55
That documentation page will be updated when this pull request is reviewed: https://github.com/cBioPortal/cbioportal/pull/1391

**Comment by ersinciftci** [comment] 2016-07-06 16:28
https://github.com/cBioPortal/cbioportal/pull/1458 I added an -n option to metaImport, and it passes along to validateData, and the default value is False. I think that's what you asked for @ecerami ?

**Comment by pieterlukasse** [comment] 2016-07-07 09:11
For completeness, my *preferred* option would be to have something like tomcat does now as well: even before you install any web applications, you can already see that the tomcat installation went well (see screenshot). Why don't we do that for cBioPortal? I.e. the installation documentation would describe the steps up to getting the homepage to work. When going to the homepage for the first time, users will be greeted by a nice green success banner (just like with tomcat), telling them that the installation executed successfully and that they can proceed with the next step, which is *data loading*.

Tomcat example (for inspiration):
![image](https://cloud.githubusercontent.com/assets/2900303/16648155/fa93540a-4432-11e6-90ad-e69e32093cc0.png)


cBioPortal idea:

![image](https://cloud.githubusercontent.com/assets/2900303/16648135/dcf0fd26-4432-11e6-8786-e63ae7137646.png)

**instead** of the current message:

![image](https://cloud.githubusercontent.com/assets/2900303/16648195/26d8002e-4433-11e6-9ab4-babe56d7db4f.png)

What do you think? Should I log this in a ticket so that it can be implemented in a *next* PR? I see you already implemented the -n option, so we can keep that for now. But ideally have something like the above at some point?

**Comment by ersinciftci** [comment] 2016-07-11 18:12
@pieterlukasse It makes great sense to me.

**Comment by pieterlukasse** [comment] 2016-07-12 07:45
@ersinciftci @ecerami : shall I log the idea above (the green banner) in a new ticket? Then we can close this one.

**Comment by ecerami** [comment] 2016-07-12 13:48
@pieterlukasse sure, go ahead.

**Comment by pieterlukasse** [comment] 2016-07-13 08:12
@ecerami thanks. I logged it at #1485. Closing this one since it is solved by #1474

**Closed by pieterlukasse** 2016-07-13 08:12 UTC
Labels: in progress
