### ISSUE TITLE
Disable user authorization

### ISSUE THREAD

**Issue by seqseek** [cBioPortal/cbioportal#13] opened 2015-05-06 22:00 UTC
Hi cBioPortal team, 

Thank you for making the source code public!  It has been very useful.  I went through the instructions and installed a local copy of cbioportal.  The issue that I have right now is I can't bypass the login page.   Probably there are some settings that I need to set in portal.properties to disable it but I have no idea how since I'm not that familiar with the whole framework.  Would you please tell me how to disable google authorization and skip the login page?  Thank you so much!

By the way,  I also followed your instructions to add users in mysql but it complained about "missing client_id".  

Best,
Jia

**Comment by ecerami** [comment] 2015-05-07 00:39
I encountered the very same issue just yesterday!  The issue is occurring because portal.properties.EXAMPLE had authentication enabled by default (yesterday I changed it, so that the default is no authentication.)

To fix, you need the very latest code with an updated portal.properties.EXAMPLE.  Try the following:

git pull
cd src/main/resources
cp portal.properties.EXAMPLE portal.properties
[edit portal.properties, as needed]
mvn -DskipTests clean install
cp portal/target/cbioportal.war $CATALINA_HOME/webapps/
open browser and go to:  http://localhost:8080/cbioportal/

Let me know if that works, and I will close the issue.

**Comment by seqseek** [comment] 2015-05-07 13:47
It works!!!  Thank you so much!

**Comment by ecerami** [comment] 2015-05-07 14:00
Bug fixed;  verified by @seqseek.  Closing.

**Closed by ecerami** 2015-05-07 14:00 UTC
