### ISSUE TITLE
Study view sample+patient count should not wait for session service

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6628] opened 2019-09-19 21:59 UTC
we should always display the sample + patient count at the top of study view even when session service fails:

<img width="415" alt="Screen Shot 2019-09-19 at 6 10 15 PM" src="https://user-images.githubusercontent.com/1334004/65284818-c2724200-db08-11e9-8f30-0d081aa29a06.png">

**Comment by inodb** [comment] 2019-09-19 22:01
Do you think you could look at this @kalletlak ? Feel free to unassign yourself if  you're busy

**Comment by jjgao** [comment] 2019-09-19 22:03
@Luke-Sikina you can help with this since you just make some change to it?

**Comment by jjgao** [comment] 2019-09-19 22:04
notifying @alisman

**Comment by alisman** [comment] 2019-09-20 21:25
@Luke-Sikina let discuss Monday about how to reproduce this

**Comment by alisman** [comment] 2019-10-02 16:45
@inodb, @Luke-Sikina and I tried to reproduce this in many different ways.   i threw error, put sleep in fetchUserSettings promise, used http rewriting (CHarles proxy) to return 503 response.  nothing kept the counts from showing up.  gonna close this unless we see it again

**Closed by alisman** 2019-10-02 16:45 UTC
Labels: bug, priority, study page
