### ISSUE TITLE
missing fusion in patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2561] opened 2017-06-09 20:20 UTC
For each fusion, we are suppose to show two entries, but currently we only show one.

http://www.cbioportal.org/case.do#/patient?sampleId=P-0002296-T01-IM3&studyId=msk_impact_2017

![image](https://user-images.githubusercontent.com/840895/26993020-5cdcd9fa-4d2f-11e7-95b8-5cdf03113f48.png)

![image](https://user-images.githubusercontent.com/840895/26993033-69c1a196-4d2f-11e7-9c4f-2ab6a359a4d8.png)

![image](https://user-images.githubusercontent.com/840895/26993040-71491138-4d2f-11e7-9d7d-8212a586ef47.png)

**Comment by onursumer** [comment] 2017-06-12 17:48
Seems like the problem is that mutation id generator does not really work for fusions, so we ended up incorrectly merged fusions:
```JavaScript
function generateMutationIdByEvent(m: Mutation): string {
    return [m.gene.chromosome, m.startPosition, m.endPosition, m.referenceAllele, m.variantAllele].join("_");
}
```

@jjgao suggested to consider `gene symbol` and `protein change` as well when generating the mutation id.

@adamabeshouse what do you think? Should we update the mutation id generator function, or try to handle fusions in a different way?

**Comment by adamabeshouse** [comment] 2017-06-12 18:22
It would be a quick, easy, and elegant fix to update the mutation id generator :)

**Comment by jjgao** [comment] 2017-06-13 14:24
@onursumer @adamabeshouse: could you fix it soon in hotfix?

**Comment by onursumer** [comment] 2017-06-13 16:42
@jjgao yes this can be fixed in hotfix.

@adamabeshouse @alisman If we are gonna fix this in hotfix, I would like to skip tests, since all the functionality related to generating id and merging mutations are moved into StoreUtils. The structure in hotfix branch is outdated and not ideal for writing tests. The main idea behind the `StoreUtils` was to make testing easier.

Should I go ahead and add a quick temporary hotfix? I will need to apply the same fix to the release branch together with tests, since it won't be possible to merge the hotfix into release without a conflict.

**Closed** 2017-06-13 22:40 UTC
Labels: bug, critical, refactoring
