### ISSUE TITLE
Sample data fetched before sample ID is retrieved

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal#4582] opened 2018-08-06 09:15 UTC
In a local instance, sometimes the message "Can't find patient X in study Y" appears, while the patient including clinical data is present. I have not been able to reproduce this on the public portal.

In the example below, only clinical data is available for the patient, but this also appeared for other patients that have genomic data available.

<img width="990" alt="screen shot 2018-08-02 at 12 06 41" src="https://user-images.githubusercontent.com/9624990/43707708-fa598f94-9968-11e8-8b40-75a7ef5f1980.png">

It seems something goes wrong with the order of calls. Before the sample ID is retrieved, calls for GISTIC, mutation and clinical data are done:

![screen shot 2018-08-06 at 12 27 04](https://user-images.githubusercontent.com/9624990/43712075-3fa29eb8-9975-11e8-8205-00724152b9f5.png)

ps. I removed some instance-specific information such as study id, sample id, host & origin.

**Comment by jjgao** [comment] 2018-08-06 14:57
@alisman @inodb any insights?

**Comment by alisman** [comment] 2018-08-06 15:05
I think I may have seen this when using local dev server and you edit a file, get a hot reload, and then this message shows up.  does that sound familiar?

**Comment by jjgao** [comment] 2018-08-06 15:50
Maybe it's related to the two failed fetch? We saw this warning earlier when the page failed some AJAX call.

**Comment by pieterlukasse** [comment] 2018-08-09 09:50
@alisman it is not on a dev server. Happens on a regular installation.

**Comment by pieterlukasse** [comment] 2018-08-13 09:08
seems to be related to this one https://github.com/cBioPortal/cbioportal/issues/4448

**Comment by pieterlukasse** [comment] 2018-08-13 09:25
@jjgao @alisman I found the issue. It has to do with a failed call to the session service. By disabling the failing call at https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/components/query/QueryStore.ts#L495, I was able to stop this error from ocurring. See https://github.com/thehyve/cbioportal-frontend/commit/b58d29ac71b1df419ed978013cc68ee749656692. So, steps to reproduce:
- install cBioPortal without session service
- go to patient view
- the call above will fail with HTTP 500
- subsequent calls will (sometimes) be affected, resulting in the error shown in the screenshot posted by @sandertan

**Comment by jjgao** [comment] 2018-08-13 17:14
Thanks, @pieterlukasse!

Agreed that we should handle AJAX call errors in a better way.

And I am not sure why we call session service in the patient view page? @alisman

**Comment by alisman** [comment] 2018-08-13 17:26
will check it out.  Thanks Pieter

**Comment by pieterlukasse** [comment] 2018-08-20 14:53
Why was this closed if this PR is not merged yet https://github.com/cBioPortal/cbioportal-frontend/pull/1378 ?

**Comment by inodb** [comment] 2018-08-20 14:56
@pieterlukasse if you put fix #issuenumber in the pr it will automatically close once merged to master. See: https://github.com/cBioPortal/cbioportal/pull/4640

**Closed** 2018-10-04 09:21 UTC
Labels: bug, patient page
