### ISSUE TITLE
data validation failed on cbioportal public data

### ISSUE THREAD

**Issue by cbio1** [cBioPortal/cbioportal#2515] opened 2017-05-31 20:36 UTC
The same script worked on acc_tcga but failed on brca_metabric:

> `$ core/src/main/scripts/importer/validateData.py -s ~/Downloads/cbioportal_public_data/datahub2/public/unzipped/brca_metabric/ -u http://localhost:8080/
> INFO: -: Running validation from cBioPortal version 1.6.1
> 
> ERROR: meta_CNA.txt: Invalid stable id for genetic_alteration_type 'COPY_NUMBER_ALTERATION', data_type 'DISCRETE'; expected one of [cna, cna_rae, cna_consensus, gistic]; value encountered: 'brca_metabric_cna'
> 
> ERROR: meta_expression.txt: Invalid stable id for genetic_alteration_type 'MRNA_EXPRESSION', data_type 'CONTINUOUS'; expected one of [mrna_U133, rna_seq_mrna, rna_seq_v2_mrna, mirna, mrna, rna_seq_mrna_capture]; value encountered: 'brca_metabric_mrna'
> 
> ERROR: meta_mutations_extended.txt: Invalid stable id for genetic_alteration_type 'MUTATION_EXTENDED', data_type 'MAF'; expected one of [mutations]; value encountered: 'brca_metabric_mutations'
> 
> INFO: meta_study.txt: Validation of meta file complete
> 
> ERROR: -: No sample attribute file detected
> Validation of study failed.`
> 
> 
>

**Comment by pieterlukasse** [comment] 2017-06-02 11:42
thanks for reporting it. This is an issue in https://github.com/cbioportal/datahub. The stable_id field in the metafiles of the study should not include the study id. @ritikakundra could you check this one and see what the best fix is (directly in the files or rather in the upstream pipeline that produces the files)?

**Comment by pieterlukasse** [comment] 2017-06-02 11:45
@cbio1 you can work around it for now by editing the corresponding `meta_*.txt` files and making sure the field `stable_id` corresponds to the expected value reported in the error messages.

**Comment by sandertan** [comment] 2017-06-02 15:41
The same issue on datahub is logged here: https://github.com/cBioPortal/datahub/issues/30

**Comment by cbio1** [comment] 2017-06-02 15:44
@pieterlukasse  many thanks!

**Comment by pieterlukasse** [comment] 2017-06-07 14:59
closing this one since it is a duplicate of https://github.com/cBioPortal/datahub/issues/30

**Closed by pieterlukasse** 2017-06-07 14:59 UTC
Labels: data
