### ISSUE TITLE
Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'

### ISSUE THREAD

**Issue by mkzia** [cBioPortal/cbioportal#7212] opened 2020-02-24 17:08 UTC
I am getting `Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'` error when I run the container `cbioportal-container`. 

The full log from the container follows:

```
root@7d0ac6dc2a05:/# /bin/sh -c 'java ${JAVA_OPTS} -jar webapp-runner.jar /cbioportal-webapp'
Adding Context  for /cbioportal-webapp
Feb 24, 2020 4:52:05 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Feb 24, 2020 4:52:05 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Feb 24, 2020 4:52:06 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Feb 24, 2020 4:52:06 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.37
Feb 24, 2020 4:52:06 PM org.apache.catalina.startup.SetContextPropertiesRule begin
WARNING: [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
Feb 24, 2020 4:52:06 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Feb 24, 2020 4:52:12 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Feb 24, 2020 4:52:12 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 24, 2020 4:52:12 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheMapUtil': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
### The error may exist in URL [jar:file:/cbioportal-webapp/WEB-INF/lib/persistence-mybatis-3.2.4-dirty-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/MolecularProfileMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT                   genetic_profile.GENETIC_PROFILE_ID AS "molecularProfileId",         genetic_profile.STABLE_ID AS "stableId",         genetic_profile.CANCER_STUDY_ID AS "cancerStudyId",         cancer_study.CANCER_STUDY_IDENTIFIER AS "cancerStudyIdentifier"                       ,             genetic_profile.GENETIC_ALTERATION_TYPE AS "molecularAlterationType",             genetic_profile.DATATYPE AS "datatype",             genetic_profile.NAME AS "name",             genetic_profile.DESCRIPTION AS "description",             genetic_profile.SHOW_PROFILE_IN_ANALYSIS_TAB AS "showProfileInAnalysisTab",             genetic_profile.PIVOT_THRESHOLD AS "pivotThreshold",             genetic_profile.SORT_ORDER AS "sortOrder",             genetic_profile.GENERIC_ASSAY_TYPE AS "genericAssayType"                                   FROM genetic_profile         INNER JOIN cancer_study ON genetic_profile.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID         INNER JOIN reference_genome ON cancer_study.REFERENCE_GENOME_ID = reference_genome.REFERENCE_GENOME_ID                                                     LIMIT ? OFFSET ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5278)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
### The error may exist in URL [jar:file:/cbioportal-webapp/WEB-INF/lib/persistence-mybatis-3.2.4-dirty-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/MolecularProfileMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT                   genetic_profile.GENETIC_PROFILE_ID AS "molecularProfileId",         genetic_profile.STABLE_ID AS "stableId",         genetic_profile.CANCER_STUDY_ID AS "cancerStudyId",         cancer_study.CANCER_STUDY_IDENTIFIER AS "cancerStudyIdentifier"                       ,             genetic_profile.GENETIC_ALTERATION_TYPE AS "molecularAlterationType",             genetic_profile.DATATYPE AS "datatype",             genetic_profile.NAME AS "name",             genetic_profile.DESCRIPTION AS "description",             genetic_profile.SHOW_PROFILE_IN_ANALYSIS_TAB AS "showProfileInAnalysisTab",             genetic_profile.PIVOT_THRESHOLD AS "pivotThreshold",             genetic_profile.SORT_ORDER AS "sortOrder",             genetic_profile.GENERIC_ASSAY_TYPE AS "genericAssayType"                                   FROM genetic_profile         INNER JOIN cancer_study ON genetic_profile.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID         INNER JOIN reference_genome ON cancer_study.REFERENCE_GENOME_ID = reference_genome.REFERENCE_GENOME_ID                                                     LIMIT ? OFFSET ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy52.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy76.getAllMolecularProfilesInStudies(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy77.getAllMolecularProfilesInStudies(Unknown Source)
	at org.cbioportal.persistence.mybatis.MolecularProfileMyBatisRepository.getAllMolecularProfiles(MolecularProfileMyBatisRepository.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:328)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy79.getAllMolecularProfiles(Unknown Source)
	at org.cbioportal.persistence.mybatis.util.CacheMapUtil.populateMolecularProfileMap(CacheMapUtil.java:110)
	at org.cbioportal.persistence.mybatis.util.CacheMapUtil.initializeCacheMemory(CacheMapUtil.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 23 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'genetic_profile.GENERIC_ASSAY_TYPE' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 73 more

----------------------------------------------------------------------------------------------------------------
-- OncoKB requires a token to access the latest data.
-- You will not be able to use OncoKB service within your instance without an access token.
-- Please review OncoKB terms(https://www.oncokb.org/terms) and register an account accordingly.
-- Thank you.
----------------------------------------------------------------------------------------------------------------
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.ApplicationContext log
INFO: Set web app root system property: 'cbioportal.20200221-2000' = [/cbioportal-webapp/]
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing log4j from [classpath:log4j.properties]
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
SEVERE: Context [] failed in [org.apache.catalina.core.StandardContext] lifecycle. Allowing Tomcat to shutdown.
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.ApplicationContext log
INFO: Shutting down log4j
ServletContextListener destroyed
Feb 24, 2020 4:52:17 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Feb 24, 2020 4:52:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
WARNING: The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Feb 24, 2020 4:52:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
WARNING: The web application [ROOT] registered the JDBC driver [com.mysql.fabric.jdbc.FabricMySQLDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Feb 24, 2020 4:52:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
Feb 24, 2020 4:52:17 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
```

Describe results:

```
MySQL [cbioportal]> describe genetic_profile;
+------------------------------+--------------------+------+-----+---------+----------------+
| Field                        | Type               | Null | Key | Default | Extra          |
+------------------------------+--------------------+------+-----+---------+----------------+
| GENETIC_PROFILE_ID           | int(11)            | NO   | PRI | NULL    | auto_increment |
| STABLE_ID                    | varchar(255)       | NO   | UNI | NULL    |                |
| CANCER_STUDY_ID              | int(11)            | NO   | MUL | NULL    |                |
| GENETIC_ALTERATION_TYPE      | varchar(255)       | NO   |     | NULL    |                |
| DATATYPE                     | varchar(255)       | NO   |     | NULL    |                |
| NAME                         | varchar(255)       | NO   |     | NULL    |                |
| DESCRIPTION                  | mediumtext         | YES  |     | NULL    |                |
| SHOW_PROFILE_IN_ANALYSIS_TAB | tinyint(1)         | NO   |     | NULL    |                |
| PIVOT_THRESHOLD              | float              | YES  |     | NULL    |                |
| SORT_ORDER                   | enum('ASC','DESC') | YES  |     | NULL    |                |
+------------------------------+--------------------+------+-----+---------+----------------+
10 rows in set (0.001 sec)
```

Using this database SQL file `https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql` which is missing the create statement for `genetic_profile.GENERIC_ASSAY_TYPE`

**Comment by dippindots** [comment] 2020-03-08 19:48
Hi @mkzia, the `GENERIC_ASSAY_TYPE` field has been added into the genetic_profile table since version `v2.12.1`, https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/migration.sql#L747-L750. 

If you are using the latest version of the cbioportal. The solution to this issue would be updating your database schema by following the instruction: https://docs.cbioportal.org/3.-cbioportal-maintenance/updating-your-cbioportal-installation

**Comment by mkzia** [comment] 2020-03-09 15:09
OK. I was using the wrong version of the sql file. You guys need to update the link on this page: 
https://github.com/cBioPortal/datahub/blob/master/seedDB/README.md

**Comment by dippindots** [comment] 2020-03-09 15:48
Hi @mkzia, any suggestion to improve the document and make it much clear? In the seedDB document, we have this:

> This schema is required for cBioPortal release versions:
> - **2.0.0**
> When using a release version **> 2.0.0**, a migration step to a new database schema might be required. The migration process is described [here](https://github.com/cBioPortal/cbioportal/blob/master/docs/Updating-your-cBioPortal-installation.md#running-the-migration-script).

IMHO, it's already mentioned that if you want to use a higher cbioportal version (>v2.00), you need to run the migration code by following the migration step. Please feel free to give us your suggestions, thanks!

**Comment by mkzia** [comment] 2020-03-09 15:52
Hi @dippindots,

In the line `Schema 2.7.3: SQL file with create table statements` the link is pointing to https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql. 

Maybe it should point to https://raw.githubusercontent.com/cBioPortal/cbioportal/master/db-scripts/src/main/resources/cgds.sql instead. 

Thanks!

**Comment by dippindots** [comment] 2020-03-09 15:56
@mkzia I will close this issue now, but please follow up if you have any suggestions about this document! Thank you!

**Closed by dippindots** 2020-03-09 15:56 UTC

**Comment by dippindots** [comment] 2020-03-09 15:57
Hi @mkzia, the cbioportal `version2.0.0` is using the database schema `Schema 2.7.3`. That's why we point to that link.

**Comment by mkzia** [comment] 2020-03-09 17:07
Hi @dippindots,

Sorry to keep bugging you, but now I am encountering the following errors when I try to validate the test study:

```
ERROR: meta_gsva_pvalues.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
ERROR: meta_gsva_scores.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
ERROR: data_cancer_type.txt: line 1: column 5: Unknown parent for cancer type 'brca-es0'; value encountered: 'Breast'
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'brca-es0'
```

I am following the instructions from https://github.com/cBioPortal/cbioportal/blob/master/docs/Load-Sample-Cancer-Study.md#set-the-portal_home-environment-variable. 

I am using the latest version of the SQL schema and cbioportal container. 

Thanks!

**Comment by dippindots** [comment] 2020-03-09 17:31
No worries! Are you trying to import `study_es_0`? If so, have you tried to import `gene panel`: https://github.com/cBioPortal/cbioportal/blob/master/docs/Load-Sample-Cancer-Study.md#import-gene-panel-for-sample-study before import the whole study?

**Comment by mkzia** [comment] 2020-03-09 17:33
Yes. I was able to successfully load the gene panel. Then I tried validating the study and it is failing. 

Thanks!

**Comment by dippindots** [comment] 2020-03-09 17:43
Cool, one more question, have you imported the seed database successfully? I think the `study_es_0` needs to import the seed database first.

**Comment by mkzia** [comment] 2020-03-09 17:48
From what I understand, running the following docker command does that

```
docker run -d --restart=always \
  --name=cbioDB \
  --net=cbio-net \
  -e MYSQL_ROOT_PASSWORD='P@ssword1' \
  -e MYSQL_USER=cbio \
  -e MYSQL_PASSWORD='P@ssword1' \
  -e MYSQL_DATABASE=cbioportal \
  -v /<path_to_save_mysql_db>/db_files/:/var/lib/mysql/ \
  -v /<path_to_seed_database>/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro \
  -v /<path_to_seed_database>/seed-cbioportal_<genome_build>_<seed_version>.sql.gz:/docker-entrypoint-initdb.d/seed_part1.sql.gz:ro \
  mysql:5.7```

I checked one of the tables, 
```
MySQL [cbioportal]> select count(*) from cosmic_mutation;
+----------+
| count(*) |
+----------+
|  1533789 |

```

**Comment by mkzia** [comment] 2020-03-09 17:57
It doesn't seem like the seed database was imported because the GENESET_VERSION is empty. 

```
MySQL [cbioportal]> select * from info;
+-------------------+-----------------+
| DB_SCHEMA_VERSION | GENESET_VERSION |
+-------------------+-----------------+
| 2.12.3            | NULL            |
+-------------------+-----------------+
1 row in set (0.001 sec)
```

**Comment by mkzia** [comment] 2020-03-09 18:03
And I tried to reimport the database again by running the following commands, but I get an error. 

```
root@ea3815f51b37:/tmp# mysql -u cbio -pP@ssword1 -h cbioDB cbioportal < cgds.sql 
root@ea3815f51b37:/tmp# mysql -u cbio -pP@ssword1 -h cbioDB cbioportal < seed-cbioportal_hg19_v2.7.3.sql 
ERROR 1054 (42S22) at line 275: Unknown column 'CYTOBAND' in 'field list'
```

**Comment by dippindots** [comment] 2020-03-09 18:11
Yes, that will give an error since the database schema is different. It looks like the issue is about the seed database has not been imported correctly.

One possible solution is:
1. remove all the tables from the database
2.import database `schema2.7.3` from here: https://raw.githubusercontent.com/cBioPortal/cbioportal/v2.0.0/db-scripts/src/main/resources/cgds.sql
3. import seed database as you did
4. create a new sql file and run migration sql: https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/migration.sql#L560-L814

**Comment by mkzia** [comment] 2020-03-09 18:32
OK. So I followed your instructions and now I get this

```
mysql> select * from info;
+-------------------+-----------------+
| DB_SCHEMA_VERSION | GENESET_VERSION |
+-------------------+-----------------+
| 2.12.3            | msigdb_6.1      |
+-------------------+-----------------+
1 row in set (0.00 sec)
```

But I am still getting the following errors:

```
INFO: meta_gsva_pvalues.txt: Validation of meta file complete
ERROR: meta_gsva_pvalues.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'

INFO: meta_gsva_scores.txt: Validation of meta file complete
ERROR: meta_gsva_scores.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
```

contents of meta_gsva_pvalues.txt

```
cancer_study_identifier: study_es_0
genetic_alteration_type: GENESET_SCORE
datatype: P-VALUE
stable_id: gsva_pvalues
source_stable_id: gsva_scores
profile_name: Pvalues of GSVA scores on oncogenic signatures gene sets
profile_description: Pvalues GSVA scores using mRNA expression data
data_filename: data_gsva_pvalues.txt
geneset_def_version: msigdb_6.1
```

Not sure what is going on. Is there a specific way to restart the Tomcat server?

**Comment by dippindots** [comment] 2020-03-09 19:22
I think this may help. Can you try these steps:
1. `docker stop cbioportal-container`
2. `docker rm cbioportal-container`
3. restart the container: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker#step-6-run-the-cbioportal-web-server

**Comment by mkzia** [comment] 2020-03-09 20:30
Still getting the same error:

```
root@656595ed05aa:/cbioportal/core/src/main/scripts/importer# ./validateData.py -s ../../../test/scripts/test_data/study_es_0/ -n |grep ERROR
ERROR: meta_gsva_pvalues.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
ERROR: meta_gsva_scores.txt: `geneset_def_version` is different from the geneset_version in the database; value encountered: 'msigdb_6.1'
Validation of study failed.
```

**Comment by dippindots** [comment] 2020-03-09 20:40
Ok, at least we exclude one possible reason. Just wondering whether you are following this command: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/example_commands#importing-data? The another reason might be you are not passing in the `-u` parameter (e.g. `-u http://cbioportal-container:8080`)

**Comment by mkzia** [comment] 2020-03-09 20:53
Thanks!
It turns out that I needed to remove the `-n` option and use the `-u` option instead:

```
./validateData.py -s ../../../test/scripts/test_data/study_es_0/  -u http://localhost:8080 
```

**Comment by dippindots** [comment] 2020-03-09 21:01
Nice! Glad to help!

**Comment by dippindots** [comment] 2020-03-09 21:09
If you have any further questions related to data or deployment, please feel free to post your question in this [google group](https://groups.google.com/forum/#!forum/cbioportal/join). Thanks!
