### ISSUE TITLE
ResultsView Comparison: Switching Generic Assay profiles does not update data

### ISSUE THREAD

**Issue by MatthijsPon** [cBioPortal/cbioportal#10520] opened 2024-01-08 10:50 UTC
If you have multiple generic assays loaded under the same 'generic_assay_type', they aggregate into a single tab.  However, when selecting between the different datasets in the ResultsView comparison view, the data is not updated. It seems like there is no request being made to the backend when switching.

**Reproduce:**
1. Select study ccle_broad_2019
2. Query for **TP53**
3. Click **Comparison** tab
4. Click **Treatment Response** sub-tab ([direct link](https://www.cbioportal.org/results/comparison?cancer_study_list=ccle_broad_2019&tab_index=tab_visualize&case_set_id=ccle_broad_2019_all&Action=Submit&gene_list=TP53&comparison_subtab=generic_assay_treatment_response))
5. Switch between the different datasets using the dropdown

Dataset 1:
<img width="991" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/63122826/4519a416-09b6-40da-91f1-d00e511dd12e">

Dataset 2:
<img width="850" alt="image" src="https://github.com/cBioPortal/cbioportal/assets/63122826/c3cf1c28-9563-44ea-b431-5d3097938e4c">

**Comment by baeywen** [comment] 2024-01-26 23:41
till 1/26/2024, the issue has not been fixed in https://www.cbioportal.org/. here is example to reproduce the bug. 
under https://www.cbioportal.org/study/summary?id=ccle_broad_2019. compare based on any grouping, in the result page, click 'Treatment Response', then switch different "Data set", the result below won't update when different "data set" selected.
![image](https://github.com/cBioPortal/cbioportal/assets/50840241/e01ae9a0-35a8-41c9-bea9-a39a54ecea68)

**Comment by TJMKuijpers** [comment] 2024-02-05 11:47
The issue seems to be introduced in [this PR ](https://github.com/cBioPortal/cbioportal-frontend/pull/4686).

**Closed** 2024-07-01 18:15 UTC
