### ISSUE TITLE
Why cBioportal can be accessed after machine restart ?

### ISSUE THREAD

**Issue by lakhujanivijay** [cBioPortal/cbioportal#6487] opened 2019-08-09 06:57 UTC
Hi,

I have installed cBioPortal using docker and it is working fine till the time I restart my machine. Every time I do that, I can no longer access the local instance.  Is it something related with mounting volumes using docker; like it is being unmounted on restart. Any guesses ?

**Comment by kalletlak** [comment] 2019-08-09 18:06
duplicate of https://github.com/cBioPortal/cbioportal/issues/6488

**Closed by kalletlak** 2019-08-09 18:06 UTC
Labels: duplicate
