### ISSUE TITLE
Treatments endpoint 404'ing on public portal

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7029] opened 2020-01-21 16:59 UTC
curl 'https://www.cbioportal.org/api/treatments/fetch' -H 'authority: www.cbioportal.org' -H 'accept: application/json' -H 'origin: https://www.cbioportal.org' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36' -H 'content-type: application/json' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://www.cbioportal.org/results?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'cookie: _ga=GA1.2.1764028159.1557761784; mp_96b84420a1a32e448f73e7b9ffccebdb_mixpanel=%7B%22distinct_id%22%3A%20%2216ab1d6770f3af-0a7842b0ab7e5a-37607603-1aeaa0-16ab1d67710b0f%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fgithub.com%2FcBioPortal%2Fcbioportal%22%2C%22%24initial_referring_domain%22%3A%20%22github.com%22%7D; mp_a37bac8664a332481726ae49603f9f63_mixpanel=%7B%22distinct_id%22%3A%20%22fc475e52-7243-4961-acd4-23e53d287e76%22%7D; amplitude_id_fef1e872c952688acd962d30aa545b9ecbioportal.org=eyJkZXZpY2VJZCI6ImY5YWE0MDJkLWZkYmQtNGMwMS05Mzg2LWM1NDk2Y2U3YzA3MlIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTU3Njc3NTY5OTQ2MywibGFzdEV2ZW50VGltZSI6MTU3Njc3NTY5OTQ2MSwiZXZlbnRJZCI6MCwiaWRlbnRpZnlJZCI6Mywic2VxdWVuY2VOdW1iZXIiOjN9; JSESSIONID=D3991952C72E556DD77210571CE17E17; _gid=GA1.2.308160979.1579619869; _gat=1' --data-binary '{"studyIds":["coadread_tcga_pub"]}' --compressed

**Comment by inodb** [comment] 2020-01-21 17:12
@alisman isn't this expected? It's using generic assay endpoint now right? Did you notice this using latest frontend?

**Comment by dippindots** [comment] 2020-01-21 19:39
@alisman I cannot reproduce this issue, if the `release-3.2.0` merged into the frontend, we should already get rid of all `treatment` endpoints.

**Closed** 2020-01-21 19:56 UTC
