### ISSUE TITLE
Timeline axis disappears if chrome window is zoomed out too far

### ISSUE THREAD

**Issue by angelicaochoa** [cBioPortal/cbioportal#2882] opened 2017-07-27 22:04 UTC
**Regular view**
<img width="626" alt="screen shot 2017-07-27 at 3 59 42 pm" src="https://user-images.githubusercontent.com/15623749/28694023-ca5e9d08-72e4-11e7-9f5d-89427782285b.png">

**Zoomed out a bit**
<img width="841" alt="screen shot 2017-07-27 at 3 59 23 pm" src="https://user-images.githubusercontent.com/15623749/28694037-d3cd18b0-72e4-11e7-8384-187f780421d3.png">

I do not have this issue with firefox or safari - just chrome.

**Comment by angelicaochoa** [comment] 2017-07-27 22:06
It looks like this is only for a certain range.. If I zoom out far enough then the timeline axis reappears.

**Comment by inodb** [comment] 2017-08-15 22:04
duplicate of #2417

**Closed** 2017-12-15 02:56 UTC
Labels: bug, hotfix, minor, refactoring
