### ISSUE TITLE
Data Sets - Query Genes, Query is not updated properly

### ISSUE THREAD

**Issue by fendor** [cBioPortal/cbioportal#1498] opened 2016-07-15 07:19 UTC
When browsing the Data Sets and selecting the Study, in the Study Summary there is the Field for Gene Queries.
When selecting some Genes and querying got these, an window opens displaying the selected genes correctly.
However, closing the recently opened window, editing the Query and resubmitting the request, will not update the query. The same window as before will be opened.

**Comment by pieterlukasse** [comment] 2016-08-17 08:59
I tried this on cbioportal.org now but could not reproduce it. Could you check again? If it still occurs, maybe add some more details like screenshots? Thanks.

**Comment by pieterlukasse** [comment] 2016-08-17 09:26
I think this might have been fixed by #1482

**Closed** 2018-07-26 16:50 UTC
