### ISSUE TITLE
revert back the change for retrieving g2s data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3286] opened 2017-10-25 13:05 UTC
Please verify that the g2s api problem (https://github.com/cBioPortal/cbioportal/issues/3259) has been solved and then revert the change in https://github.com/cBioPortal/cbioportal-frontend/pull/700.

**Comment by onursumer** [comment] 2017-10-25 18:48
@jjgao Seems like the problem is resolved with g2s API.

**Closed** 2017-10-27 19:35 UTC
Labels: refactoring
