### ISSUE TITLE
ERROR in showing CNA data in mutations tab

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2839] opened 2017-07-24 22:37 UTC
![screen shot 2017-07-24 at 6 31 37 pm](https://user-images.githubusercontent.com/12007862/28547894-166df70e-709f-11e7-8dc1-eb835b9ba2ef.png)

When I loaded CNA for mskimpact for KRAS, some showed error

**Comment by ritikakundra** [comment] 2017-07-24 22:38
![screen shot 2017-07-24 at 6 38 44 pm](https://user-images.githubusercontent.com/12007862/28547934-4a463636-709f-11e7-92ba-aa8751100e6c.png)

**Comment by inodb** [comment] 2017-07-24 22:43
Duplicate of #2784

**Closed** 2017-07-27 18:48 UTC
Labels: duplicate, refactoring
