### ISSUE TITLE
Missing Enrichment for RPPA signals

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal#5415] opened 2018-12-09 04:36 UTC
> Until recently, I was able to look for enrichments in selected tumor sets in signals from RPPA analyses, but this seems to have been removed (either the protein sub-tab under enrichments is gone, or only allows for mass spec data use). Has this feature been removed, or is there another way to access RPPA enrichments?
Matthew J. Sikora, PhD
Assistant Professor
Department of Pathology
University of Colorado Denver|Anschutz Medical Campus
![tcga enrich screenshots](https://user-images.githubusercontent.com/17375786/49693469-cf0d4700-fb41-11e8-963a-4dbd12a9b51b.png)

**Comment by jjgao** [comment] 2018-12-10 17:10
I couldn't reproduce this. Closing for now.

**Comment by khzhu** [comment] 2018-12-10 17:42
Hi @jjgao, thank you for looking into this. 
how about you query gene WNT4 only then you will not see the Protein tab on the study view.

**Comment by jjgao** [comment] 2018-12-10 17:42
from jeffpbruce@gmail.com, see [post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/dOXMYoOHgcc/mfdqZKloDwAJ)

"Kelsey and I may have identified the issue.  It looks like if you don't include a gene with a linked antibody on the RPPA in your query, the protein enrichment tab does not appear.  So when you query only WNT4, which has no associated antibody on the RPPA used by TCGA, the tab does not appear, whereas when Kelsey queried PIK3CA, which was on the array, the tab appears. I do think is a glitch that should be addressed as the enrichment analysis should not depend on protein expression data being available from the queried genes."

**Comment by jjgao** [comment] 2018-12-10 17:47
@ersinciftci would you please look into this?

When search EGFR, we can see the Protein tab under Enrichments: http://www.cbioportal.org/results/enrichments?session_id=5c0ea618e4b024a8f3efa981

But when search WNT4, there is no Protein tab: http://www.cbioportal.org/results/enrichments?session_id=5c0ea5d3e4b0264c0d23c2bd

Could you check the reason? Maybe it's b/c none of the altered samples have protein data? Or are you filtering based on query genes?

**Comment by ersinciftci** [comment] 2018-12-10 18:35
@jjgao It's done as part of @adamabeshouse 's https://github.com/cBioPortal/cbioportal-frontend/pull/1510 PR. If all the Protein profiles in the study has 0 alterations for that gene, it doesn't show the Protein tab (same for other types of profiles, too).

**Comment by adamabeshouse** [comment] 2018-12-10 19:04
@jjgao isn't that desired behavior? how can you do an enrichment analysis between two groups when one of the groups is empty?

**Comment by jjgao** [comment] 2018-12-10 20:31
@adamabeshouse @ersinciftci I agree that it's the right results, but I think it's creating some confusion as the subtabs (Mutations, CNAs, mRNA, Protein) changes when different genes are queried. Ideally, if there is protein data and there are two groups in oncoprint, we should always display the Protein tab. But in case that all protein-profiled samples are only in one group (e.g. unaltered group), the Protein tab should be grayed or at least add a message within the tab, e.g. "All samples with protein profiles are altered (or unaltered)." This should apply to other subtabs as well.

**Comment by adamabeshouse** [comment] 2018-12-10 20:33
ah okay. so I dont think we need to modify my changes from that PR, just add to the enrichments tab component

**Comment by jjgao** [comment] 2018-12-20 15:31
@ersinciftci @adamabeshouse I looked into this more and found that when querying WNT4, even if we have RPPA data in both groups, the Enrichments/Protein tab still does not show up.

http://bit.ly/2V31JGL

![image](https://user-images.githubusercontent.com/840895/50293493-b6eecf00-0441-11e9-9da2-3df7b0fc918d.png)

@adamabeshouse could you look into this as @ersinciftci is on vacation?

**Comment by adamabeshouse** [comment] 2018-12-20 20:04
there seems to be a bug in the API where it's returning 0 samples with data for the RPPA profiles

**Comment by jjgao** [comment] 2018-12-20 21:14
@adamabeshouse are you looking into the api? Or maybe @onursumer can help look together?

**Comment by ersinciftci** [comment] 2018-12-20 21:48
@jjgao Because `brca_tcga_rppa` profile doesn't have data for `WNT4` gene
```
SELECT * FROM public_test.genetic_alteration inner join gene on gene.GENETIC_ENTITY_ID = genetic_alteration.GENETIC_ENTITY_ID 
inner join genetic_profile on genetic_profile.GENETIC_PROFILE_ID = genetic_alteration.GENETIC_ENTITY_ID
where genetic_profile.STABLE_ID = 'brca_tcga_rppa' and gene.HUGO_GENE_SYMBOL = 'WNT4';
```

**Comment by adamabeshouse** [comment] 2018-12-20 21:51
@ersinciftci so then looking at the oncoprint screenshot (and confirmed with the data in resultsViewPageStore) there must be a data inconsistency, or an inconsistency with the gene panel API?

**Comment by jjgao** [comment] 2018-12-20 22:01
@ersinciftci it's not necessary for the RPPA profile to have WNT4 gene in order to test for enrichments. The idea is to test whether other genes are significantly different between the two groups. For example, there may be differently expressed proteins between the WNT4 mutant cases and wildtype cases even if WNT4 was not profiled by RPPA.

I just noticed that queryGenes were used in the query in the API. I think we should remove that.

![image](https://user-images.githubusercontent.com/840895/50313239-af96e800-0478-11e9-8c96-cc5b4d401c27.png)

**Comment by ersinciftci** [comment] 2018-12-20 22:05
@jjgao I think it works the way you described, Protein tab is just not visible due to https://github.com/cBioPortal/cbioportal/issues/5415#issuecomment-445923144 because as I said it checks if there is any molecular data for that gene in that profile and hides the tab if there is none.

**Comment by ersinciftci** [comment] 2018-12-20 22:09
And the queryGenes is not there to check if it's altered or not, it's there to exclude it from the results so that the table in the frontend wouldn't show it. None of the enrichment endpoints had query genes parameters in the beginning, but I remember that I was requested to add it because we didn't want to see them in the table.

**Comment by adamabeshouse** [comment] 2018-12-20 22:11
i think `queryGenes` is a confusing name then, it should be `excludeGenes` or something.

so then under what conditions *should* we hide the protein tab, if ever?

and there still seems to be a data inconsistency, as evident in the oncoprint screenshot..

**Comment by jjgao** [comment] 2018-12-20 22:13
@ersinciftci ah. got it. Agreed with @adamabeshouse -- better to change it to excludeGenes.

@ersinciftci how do you explain in this query (http://bit.ly/2V31JGL), there is no Protein tab?

![image](https://user-images.githubusercontent.com/840895/50293493-b6eecf00-0441-11e9-9da2-3df7b0fc918d.png)

**Comment by adamabeshouse** [comment] 2018-12-20 22:18
@ersinciftci i dont understand why it matters whether theres molecular data for the query genes in that profile, because it seems like all that matters would be having any molecular data at all in order to define the altered/unaltered groups? and then the enrichments are calculated for *other* genes in that profile w.r.t. those groups, right?

**Comment by jjgao** [comment] 2018-12-20 22:23
@adamabeshouse right, I missed that "check if there is any molecular data for that gene in that profile." It shouldn't matter.

**Comment by adamabeshouse** [comment] 2018-12-20 22:38
@ersinciftci oh I see. yeah you're right, that PR messed up the calculation of ...EnrichmentProfiles. I'll fix that

**Comment by jjgao** [comment] 2018-12-20 22:39
@adamabeshouse I don't think we added gene panels for RPPA. We should do that. Will create a ticket.

**Comment by jjgao** [comment] 2018-12-20 22:42
I guess all mysteries solved?

@ersinciftci you should turn off network for vaca :)

**Comment by jjgao** [comment] 2018-12-20 23:39
@ersinciftci @adamabeshouse logged here (https://github.com/cBioPortal/cbioportal/issues/5515) about moving the exclusion logic to frontend.

@adamabeshouse please feel free to fix it together. (also ok to leave changes to the API later.)

**Comment by adamabeshouse** [comment] 2019-01-02 21:10
fixed in `master`

**Closed by adamabeshouse** 2019-01-02 21:10 UTC
Labels: API, bug, critical, priority, results.enrichments
