### ISSUE TITLE
sv: toggling log scale on one chart should not reload all other charts

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5468] opened 2018-12-17 23:10 UTC
If I toggle log scale on the Days to Sample Collection chart, the entire page re-renders. All other charts should remain and only this one chart should need to re-render.
http://www.cbioportal.org/beta/study?id=lgg_tcga

**Comment by ersinciftci** [comment] 2018-12-19 21:50
Duplicate of https://github.com/cBioPortal/cbioportal/issues/5429

**Comment by alisman** [comment] 2019-08-06 20:37
@kalletlak can you research why this is happening?   Most likely reason is that we are doing some computation inside of a mobxpromise invoke.  When we change log scale state, that promise recomputes and automatically passes through a pending->complete cycle even though there is no actual asychronous operation.   This is a result of our use of facade mobxpromises which just process the result of underlying promises. There are a couple different solutions for this.  1. @adamabeshouse has worked on a version of mobxpromise which is not async.  2. We could stop using facade moxpromises and instead put the processling logic they contain into helper functions.  View code would be responsible for reference the underlying mobxpromises and passing the result (when complete) to these helper functions.   

One strange thing: toggleLogScale method of StudyViewPageStore actually fires twice when we click the log scale checkbox.

**Closed** 2019-08-08 15:06 UTC
Labels: frontend, good first issue, priority, study page
