### ISSUE TITLE
CNV Data discrepancies between Cbioportal webpage and cgdsr R package

### ISSUE THREAD

**Issue by Lesdormis** [cBioPortal/cbioportal#7521] opened 2020-05-19 14:53 UTC
Dear Cbioportal Developers,

I found the gene alteration data (Amplification, deep deletion) showed in Cbioportal webpage doesn't match from the data I downloaded from cgdsr package. Take AMBRA1 and TCGA-BLCA Pan Atlas as an example.
![image](https://user-images.githubusercontent.com/30546732/82341430-6a088280-99be-11ea-90f9-410e7abb8ac9.png)
In here there are 5 samples with amplification while in my R data the value "2" has 6 samples.
![image](https://user-images.githubusercontent.com/30546732/82341539-90c6b900-99be-11ea-922f-e0fa6e4dd28a.png)
Also, the total number of samples doesn't match too, 406 in webpage and 408 in R.
Could you tell me what's the reason for the discrepancies? Maybe I missed something here.

Here is my code how to get the gistic CNV data via cgdsr package in R.

library(cgdsr)
mycgds =CGDS("https://www.cbioportal.org/")
i = "blca"
df = getProfileData(mycgds, "AMBRA1",paste0(i,"_tcga_gistic"),paste0(i,"_tcga_pan_can_atlas_2018_all"))
print(table(df$AMBRA1))

Thanks!!!

**Comment by jjgao** [comment] 2020-05-22 19:31
Hi @Lesdormis thanks for reporting this to us.

I can reproduce the inconsistency you found and pinpoint to the sample [TCGA-FD-A43N-01](https://www.cbioportal.org/patient?studyId=blca_tcga_pan_can_atlas_2018&sampleId=TCGA-FD-A43N-01). It seems that we only have GAIN (1) for AMBRA1 in TCGA-FD-A43N-01 in our data files and API but somehow the R returns it as AMP (2). We will look into this more.

I would recommend you switch to our new API: https://docs.cbioportal.org/6.-web-api-and-clients/api-and-api-clients, which is also used by the webiste.

For the different numbers of samples, it was because of the different case list used.

![image](https://user-images.githubusercontent.com/840895/82691005-35e5c980-9c2b-11ea-90d1-cb724389035c.png)

**Comment by Lesdormis** [comment] 2020-05-22 19:37
Hi @jjgao 
Thanks for the response! So do you mean we should not use the cgdsr package anymore and move on to the new API, which is more trustable?

Thanks!

**Comment by jjgao** [comment] 2020-05-22 19:48
@Lesdormis we are finalizing the new API and will make it official soon. You can use the r-client of the new API if it's an easy transition for you. Otherwise, we are also thinking of linking cgds-r to the new API (this will take some time).

**Comment by Lesdormis** [comment] 2020-05-25 15:16
Hi @jjgao , sorry for troubling you again. 
I tried with the cBioPortaData package but got the same data. I am a little confused, which data should I use? The Cbioportal website, or the R client?

Here is my code,
library(cBioPortalData)
library(AnVIL)
blca = cBioDataPack("blca_tcga")
cna = as.data.frame(blca@ExperimentList$CNA@assays@data@listData)
ambra1_cna <- as.data.frame(t(cna["AMBRA1",]))
table(ambra1_cna$AMBRA1)
![image](https://user-images.githubusercontent.com/30546732/82825369-1f34b200-9e79-11ea-86c1-3ae09178e9d7.png)

Thanks very much for the help!

**Comment by jjgao** [comment] 2020-05-28 20:53
Strange. We will look into this.

**Comment by inodb** [comment] 2020-06-17 20:32
Hi @Lesdormis ! Sorry for the slow reply on this

The reason the numbers don't match is because "blca_tcga" is a different study from "blca_tcga_pan_can_atlas_2018" which is the one queried in the screenshot

If I try your code for the latter the numbers make sense:

```
> library(cBioPortalData)
> library(AnVIL)
> blca = cBioDataPack("blca_tcga_pan_can_atlas_2018")
> cna = as.data.frame(blca@ExperimentList$CNA@assays@data@listData)
> ambra1_cna <- as.data.frame(t(cna["AMBRA1",]))
> table(ambra1_cna$AMBRA1)

 -2  -1   0   1   2 
  2 167 199  35   5 
```

I can also recommend to check out the API tutorial if you plan on using the R client more: https://www.cbioportal.org/tutorials#webinar-5

Let us know if that solves your problem. Closing this for now, but feel free to re-open if it doesn't solve the problem for you.

**Closed** 2020-06-17 20:32 UTC
Labels: r-client, support
