### ISSUE TITLE
Results view bug in Safari

### ISSUE THREAD

**Issue by priti88** [cBioPortal/cbioportal#5001] opened 2018-10-11 20:40 UTC
Going back to Oncoprints from mutation tab shows red or black block
<img width="1258" alt="screen shot 2018-10-11 at 4 33 06 pm" src="https://user-images.githubusercontent.com/1380237/46832459-12328000-cd74-11e8-9289-58135b8fe2d6.png">

**Comment by jjgao** [comment] 2018-10-11 20:49
@priti88 could you reproduce it in public portal?

**Comment by tmazor** [comment] 2018-10-11 22:01
I get all black, but the same problem. I've tried a few queries and it always happens, but only in Safari.

![image](https://user-images.githubusercontent.com/10508276/46836452-7eff4780-cd7f-11e8-80fa-1ef96a4b8059.png)

http://www.cbioportal.org/index.do?cancer_study_id=acc_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=acc_tcga_pan_can_atlas_2018_cnaseq&gene_list=KRAS&geneset_list=+&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_pan_can_atlas_2018_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_pan_can_atlas_2018_gistic

**Comment by jjgao** [comment] 2018-10-11 22:13
@tmazor @priti88 thanks. I can reproduce it on Safari too -- also red. But it seems to be fixed in beta so I think we will wait until the release.

**Comment by priti88** [comment] 2018-10-12 17:09
thanks @jjgao

**Closed** 2018-10-12 17:40 UTC
Labels: bug, results.oncoprint
