### ISSUE TITLE
gene name not aligned with oncoprint in svg/pdf

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#327] opened 2015-10-08 20:01 UTC
![image](https://cloud.githubusercontent.com/assets/840895/10378170/696a3eaa-6dd5-11e5-982e-8d283f0eff1a.png)

**Comment by adamabeshouse** [comment] 2015-10-08 20:47
Is this HTML, SVG, PDF?

**Comment by jjgao** [comment] 2015-10-08 21:05
Sorry, svg & pdf

**Comment by jjgao** [comment] 2015-10-08 21:06
Not a urgent issue.

**Comment by adamabeshouse** [comment] 2015-10-09 16:00
I think we should "won't fix" this since we're about to reimplement the rendering

**Comment by jjgao** [comment] 2015-10-15 19:28
Let's keep it here so we can check in the new implementation.

**Comment by adamabeshouse** [comment] 2016-04-08 21:01
Confirmed working in new implementation

**Closed by adamabeshouse** 2016-04-08 21:01 UTC
Labels: bug, minor, wontfix
