### ISSUE TITLE
SV: filtering by some charts doesn't populate the filter bar at the top

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5331] opened 2018-11-27 18:07 UTC
Filtering from either "# of Samples Per Patient" or "Cancer Studies" chart leads to the filter being applied, but the status bar at the top doesn't list it:

![image](https://user-images.githubusercontent.com/10508276/49101784-0aa43900-f245-11e8-9092-d09d5d6d9c67.png)

![image](https://user-images.githubusercontent.com/10508276/49101931-6c64a300-f245-11e8-8132-a2334d1af0ba.png)

**Comment by ersinciftci** [comment] 2018-11-27 18:36
Duplicate of https://github.com/cBioPortal/cbioportal/issues/5265

**Comment by zhx828** [comment] 2018-12-11 01:30
@tmazor this issue has been solved.

**Closed by zhx828** 2018-12-11 01:30 UTC
Labels: frontend, study page
