### ISSUE TITLE
Error in mutations tab

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#8482] opened 2021-04-01 00:09 UTC
For https://www.cbioportal.org/results?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&data_priority=0&tab_index=tab_visualize&Action=Submit&session_id=6064e7b9e4b0242bd5d45f5f

Mutation tab doesn't load

<img width="693" alt="Screen Shot 2021-03-31 at 8 08 39 PM" src="https://user-images.githubusercontent.com/12956870/113225939-f0d3f000-925c-11eb-8b2a-a50e4348b039.png">

**Comment by onursumer** [comment] 2021-04-01 23:12
Seems like this is already fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/3690. I cannot reproduce on the latest master. This should go away once we deploy the latest frontend version.

CC: @inodb @leexgh

**Comment by inodb** [comment] 2021-04-02 19:30
fixed

**Closed by inodb** 2021-04-02 19:30 UTC
Labels: bug, frontend, results.mutations
