### ISSUE TITLE
Bug in the adding of treatments to the heatmap

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#6726] opened 2019-10-19 15:17 UTC
There is a bug in the adding of treatments to the heatmap that has recently been introduced. It is easy to reproduce:
- go to the add treatment menu in the oncoprint heatmap menu
- use the search box to search for something, say braf
- note that the number in the select all button is not updated
- if you click the select all button all the treatments are selected, not just the ones that match the search string, as was intended

In addition, and likely introduced at the same time: after clicking a treatment in the search dropdown the dropdown gets closed. This makes it more tedious to select multiple (but not all) treatments that match a certain search string.

**Comment by pvannierop** [comment] 2019-10-21 12:06
Duplicate of #6717

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-21 12:53
@pvannierop Provided the second bit also gets fixed!

**Closed** 2019-10-21 12:52 UTC
Labels: bug, hyve

**Comment by pvannierop** [comment] 2019-10-24 11:35
@Sjoerd-van-Hagen Ah ok. I did not read until that line. I will add this to our todo list.
