### ISSUE TITLE
OncoPrint: Make sure the custom mutaiton annotation code are moved over

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#3087] opened 2017-09-08 15:33 UTC
https://github.com/cBioPortal/cbioportal/pull/2896

**Comment by pieterlukasse** [comment] 2017-09-11 14:09
duplicate of https://github.com/cBioPortal/cbioportal/issues/3086

**Closed** 2017-09-11 15:23 UTC
Labels: duplicate, oncoprint, refactoring
