### ISSUE TITLE
Not receving MSK importing email notification

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/cbioportal#9023] opened 2021-11-01 18:47 UTC
From Yichao: 10 studies were scheduled to be imported to MSK portal (private DB) on Oct 29 (Fri)  but no email notification was received for the importing results. 

TODO / Done list
- Rob forwarded the log in email
- Yichao rescheduled one study again to see if the email would send on Nov 1 (Mon)

**Comment by sheridancbio** [comment] 2021-11-02 18:18
The cause here was not determined, but notification emails resumed when the order of records in the datatypes sheet was adjusted. Until the problem recurs we are closing this card.

**Closed** 2021-11-15 15:18 UTC
Labels: interrupt, cbioPortal Maintenance
