### ISSUE TITLE
Change design for adding X vs Y charts

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10362] opened 2023-09-01 13:27 UTC
Mockup from design hackathon:

https://docs.google.com/presentation/d/1t9wLcQ58RG6KQnOkngExer3b-dt-x1yNzo8NJ9mueRM/edit?pli=1#slide=id.g2450dd32ba9_0_50

**Comment by dassudip2001** [comment] 2023-09-15 06:39
I can fix this issue

**Comment by alisman** [comment] 2023-12-14 19:00
@gblaih this ticket is associated with plots tab to study view ticket

**Comment by alisman** [comment] 2023-12-14 19:01
@gblaih close this as duplicate of https://github.com/cBioPortal/cbioportal/issues/10443

**Closed by alisman** 2023-12-14 19:01 UTC
Labels: feature
