### ISSUE TITLE
Specific comparison giving an error on alterations tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9478] opened 2022-04-21 17:35 UTC
https://www.cbioportal.org/comparison/alterations?comparisonId=6261444204dc353874695a5e. Other tabs work fine: https://www.cbioportal.org/comparison/survival?comparisonId=6261444204dc353874695a5e

As reported by:
https://groups.google.com/g/cbioportal/c/fgPTVz1nwj8/m/3Plz3x8xBQAJ

There's another seemingly related bug but after further inspection it seems different: https://github.com/cBioPortal/cbioportal/issues/9480

**Comment by Luke-Sikina** [comment] 2022-04-21 18:51
I cannot reproduce this locally. I'm using the following curl:
```bash
curl 'http://localhost:8080/api/alteration-enrichments/fetch?enrichmentType=SAMPLE'   -H 'authority: www.cbioportal.org'   -H 'accept: application/json'   -H 'content-type: application/json'   --data-binary "@/path/to/request/body/foo.json"
```
[foo.zip](https://github.com/cBioPortal/cbioportal/files/8534317/foo.zip)

With the request body being:

**Comment by Luke-Sikina** [comment] 2022-04-21 19:21
This is now fixed. Closing.

**Closed by Luke-Sikina** 2022-04-21 19:21 UTC
Labels: bug
