### ISSUE TITLE
error loading patient view without mutation data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#995] opened 2016-04-01 02:46 UTC
http://www.cbioportal.org/case.do?cancer_study_id=esca_tcga&sample_id=TCGA-IG-A97H-01

**Comment by jjgao** [comment] 2016-04-15 12:21
@inodb could you fix this soon? Thanks.

**Comment by inodb** [comment] 2016-04-19 14:33
Will have a look, duplicate of #855

**Closed by inodb** 2016-04-19 14:33 UTC
Labels: critical, duplicate, hotfix
