### ISSUE TITLE
remove-study does not remove all data from database

### ISSUE THREAD

**Issue by awernibi** [cBioPortal/cbioportal#132] opened 2015-07-27 15:54 UTC
According to the documentation, I am trying to remove a formerly imported study from the mysql database (in addition to import study, I added also some data with import-patient-list, and import-study-data)

after running the following script:

$PORTAL_HOME/core/src/main/scripts/cbioportalImporter.py --jvm-args "-cp $CONNECTOR_JAR:$PORTAL_HOME/core/target/core-1.0-SNAPSHOT.jar" --command remove-study --meta-filename meta_study.txt

I compare my database backup with the current database (using mysqldbcompare).

Even though the db and the backup db should be identical, I see a number of additional rows in table genetic_alteration. 

Are there any convenient ways to import data, apart from the python script/java program?
How can I get rid of the additional data?

**Comment by fedde-s** [comment] 2016-02-09 11:23
I loaded a study with an expression data file into a cBioPortal installation of the version in commit thehyve/cBioPortal@c86a553, from the branch on which we are currently working on improving the loading pipeline. After confirming that data had been loaded into the `genetic_alteration` table, I ran the following command to remove it again:

```bash
cbioportalImporter.py --jar_path $PORTAL_HOME/core/target/core-1.1.0-SNAPSHOT.jar --command remove-study --meta_filename meta_study.txt
```
Not that the names of the command line options have changed during the first hackathon.

This did not reproduce your issue. The only differences with a database just loaded with the seed file were:

- the clinical attributes defined (as expected, since clinical attributes are defined globally when they are imported found in a data file for the first time), and
- the auto-increment trackers of tables in which data had been loaded while the study was in place.

Could you try to reproduce the issue when this branch is included into a release?

**Comment by pieterlukasse** [comment] 2016-06-16 14:38
@awernibi can we close this one?

**Closed** 2018-05-14 21:02 UTC
