### ISSUE TITLE
Left / right slider in new OncoPrint is hidden

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3733] opened 2018-01-16 01:49 UTC
I am having trouble with the left right slider in the new oncoprint. In Chrome, I don't see it, in Firefox I see it but I can't use it.. so I can only scroll left right via the trackpad (2 finger slide)...

http://bit.ly/2DyDhV7

**Comment by adamabeshouse** [comment] 2018-01-17 00:57
@alisman any ideas?

**Comment by sandertan** [comment] 2018-03-29 13:09
Any update on this? I see the scroll bar in Chrome, but am missing it Safari

http://bit.ly/2IcV0T7

When the pop-up of a cell in the OncoPrint is displayed when hovering over it, and the cursor moves to a location just inside the pop-up, scrolling is disabled (probably because it tries to scroll in the pop-up). Would it be possible to enable scrolling of the oncoprint, even when in the pop-up?

**Comment by alisman** [comment] 2018-03-29 15:39
I think I see the problem.  Will make a PR

**Comment by adamabeshouse** [comment] 2018-04-05 20:09
seems fixed in production

**Comment by tmazor** [comment] 2018-04-09 16:54
I can't scroll at all on OncoPrint. I tried Chrome & Safari & Firefox and in all three I don't see a scroll bar underneath and I also can't scroll using my trackpad.

**Comment by adamabeshouse** [comment] 2018-04-09 17:00
@tmazor can't reproduce, whats your environment?

**Comment by tmazor** [comment] 2018-04-09 17:47
Ok, I see what's happening. I can scroll using the trackpad by hovering over the scroll bar, but the scroll bar is invisible until I start scrolling. It used to be possible to scroll with the trackpad while hovering over the OncoPrint itself but that doesn't work anymore (and that's what I was trying to do before).

**Comment by schultzn** [comment] 2018-04-09 18:01
I vaguely remember that @alisman and I at some point identified this as a MacBook Pro specific issue?

**Comment by alisman** [comment] 2018-04-09 18:16
@schultzn I think this is different.   I think I have an idea how to get the old behavior back.

**Comment by jjgao** [comment] 2018-04-10 14:32
@adamabeshouse @alisman it's really tricky to scroll now b/c you have to hover over the scroll bar in order to scroll as pointed out by @tmazor  -- in both Chrome and Firefox for me. I also remember we used to be able to scroll with trackpad  when hovering on oncoprint. Could you try to support that? Is it also possible to force display the scroll bar?

**Comment by alisman** [comment] 2018-04-10 14:37
I already have a PR doing just this. Please test below:
localStorage.heroku = "cbioportal-frontend-pr-1078"

**Comment by inodb** [comment] 2018-04-13 21:08
deployed to production

**Closed by inodb** 2018-04-13 21:08 UTC
