### ISSUE TITLE
Plots tab not loading

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7758] opened 2020-08-03 22:27 UTC
... for [this query with 2 pancan studies](https://www.cbioportal.org/results/plots?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=acc_tcga_pan_can_atlas_2018%2Cchol_tcga_pan_can_atlas_2018&case_set_id=all&data_priority=0&gene_list=CDKN2A%2520MDM2%2520MDM4%2520TP53&geneset_list=%20&plots_coloring_selection=%7B%7D&plots_horz_selection=%7B%22dataType%22%3A%22PROTEIN_LEVEL%22%7D&plots_vert_selection=%7B%7D&profileFilter=0&tab_index=tab_visualize).

It is strange because when I select all pancan studies (including these two) and query the same genes, the page loads.

**Comment by dippindots** [comment] 2020-08-06 18:34
@jjgao I am working on this issue, but somehow I cannot reproduce this issue. Could you help to verify if this still an issue?

**Comment by dippindots** [comment] 2020-08-11 13:54
@jjgao I will close this ticket, if you think this issue still persist, please feel free to reopen it.

**Closed by dippindots** 2020-08-11 13:55 UTC
Labels: bug, results.plots

**Comment by jjgao** [comment] 2020-08-11 14:57
Seems working now - sorry for the confusion. Thanks.
