### ISSUE TITLE
Black dots in sample circles on genie patient

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7880] opened 2020-09-11 16:56 UTC
https://genie-private.cbioportal.org/patient?studyId=nsclc_genie_bpc&caseId=GENIE-DFCI-008085#

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/ae8ec021-1dad-4826-93f7-b8cd21a1a51f)

**Comment by adamabeshouse** [comment] 2020-09-11 20:16
so what's happening here is those dots represent a sample which doesnt seem to exist on the patient:
GENIE-DFCI-008085-6295

because the sample doesnt exist, the code can't find a number to label the dot with, so defaults to -. If you mouse over you'll see there's some issue fetching data too.

**Comment by adamabeshouse** [comment] 2020-09-17 00:07
@inodb any thoughts on this?

**Comment by jjgao** [comment] 2020-09-17 16:59
Interesting, so it's data issue. In the error message could you add the sample ID? Once that's done, maybe we can close this? @alisman

**Comment by inodb** [comment] 2020-09-17 21:54
I imagine the issue is that we do have a sample/sequencing collection date for that sample, but no sequencing data imported. Will share with Brooke and Ritika

**Comment by inodb** [comment] 2020-09-17 22:02
@adamabeshouse it still might make sense to handle this a little more elegantly. E.g. one can imagine in the future the use case where sample acquisition has been done but there is not corresponding mutation data yet. Then the dot would show up in sample acquisition, but we wouldn't have mutation data imported yet. Maybe we can show a blue dot and when you mouse over it will show the regular timeline tooltip (instead of the sample tooltip)?

**Comment by adamabeshouse** [comment] 2020-09-17 22:07
@inodb I agree we should handle it more elegantly. I feel that making it not look like a sample would be confusing, though. Here are a couple ideas:
(1) Use a question mark instead of a number (but could be confusing)
(2) Assign each unknown sample id a unique number in the SampleManager in a (temporarily) persistent way. Downside is that the numbers no longer would correspond at all to temporal order, but this maybe is a rare enough case that it doesn't really matter.

**Comment by inodb** [comment] 2020-09-17 22:23
@adamabeshouse maybe (1), but continue to use `-`? Question mark feels more "alerting", whereas it doesn't necessarily have to indicate a problem. I guess using only one symbol wouldn't handle the case of having multiple samples with missing mutation data very well, but it's kind of a corner case anyway

**Comment by adamabeshouse** [comment] 2020-09-18 18:48
@inodb gotcha, so we'll keep `-` but make the tooltip not show any error. But what should the tooltip say? @jjgao

**Comment by inodb** [comment] 2020-09-18 18:51
It can be the same as the other tooltips on the timeline (don't show the sample specific tooltip, but rather the default one)

**Closed** 2020-09-21 16:26 UTC
