### ISSUE TITLE
iviz: support finer granularity in histogram

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2423] opened 2017-05-09 21:02 UTC
so that we can select by finer level

**Comment by pieterlukasse** [comment] 2017-08-22 09:53
duplicate of https://github.com/cBioPortal/cbioportal/issues/1765

**Comment by pieterlukasse** [comment] 2017-08-22 09:54
I added some comments on https://github.com/cBioPortal/cbioportal/issues/1765.

**Closed** 2018-06-28 21:05 UTC
Labels: duplicate
