### ISSUE TITLE
Dauthenticate flag causes failure in deploying cBioPortal

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal#6305] opened 2019-06-21 15:14 UTC
I am trying to deploy cBioPortal with Keycloak (without Docker) and I run to this exception: `org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cacheMapUtil': Invocation of init method failed; nested exception is org.apache.ibatis.builder.IncompleteElementException: Could not find SQL statement to include with refid 'org.cbioportal.persistence.mybatis.GeneMapper.select'`

The command to deploy is: `java -jar -Dauthenticate=saml portal/target/dependency/webapp-runner.jar portal/target/cbioportal.war`

The exception does not appear when I use `-Dauthenticate=false`. I have tried the branches `master`, `v3.0.1`, and `v3.0.0`, and I see this exception in all of them.

Somehow it looks related to the changes on `portal.properties` introduced in #6046 by @inodb. However, this issue looks very similar to #5816 so I am also mentioning @pieterlukasse @n1zea144 @khzhu and @jjgao

**Comment by Sjoerd-van-Hagen** [comment] 2019-06-21 15:26
@inodb we would like to work on the fix for the metadata tags issue but this is blocking us. Can you have a look?

**Comment by pvannierop** [comment] 2019-06-26 07:29
@inodb 
I in parallel encountered this problem. The setting -Dauthenticate= *noauthsessionservice* also results in this error.

**Comment by oplantalech** [comment] 2019-06-27 07:33
I also have the same error when loading a study with `cbioportalImporter.py` and using `-Dauthenticate=false`.

**Comment by pieterlukasse** [comment] 2019-06-27 10:38
CC @n1zea144

**Comment by n1zea144** [comment] 2019-06-28 14:47
@Sjoerd-van-Hagen @inodb 
As @oplantalech points out, this looks like the "old issue back again".

I don't understand why this is cropping up now, but the problem may be that applicationContext-web.xml is being loaded before applicationContext-business.xml.

Inside [applicationContext-web.xml](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/resources/applicationContext-web.xml#L68) is where [InvolvedCancerStudyExtractorInterceptor](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/cbioportal/web/util/InvolvedCancerStudyExtractorInterceptor.java#L77) is loaded which loads [CacheMapUtil](https://github.com/cBioPortal/cbioportal/blob/master/persistence/persistence-mybatis/src/main/java/org/cbioportal/persistence/mybatis/util/CacheMapUtil.java) which autowires in many MyBatis Repositories.  The MyBatis repositories come in via [applicationContext-business.xml](https://github.com/cBioPortal/cbioportal/blob/master/business/src/main/resources/applicationContext-business.xml#L27).

There are a few places within web.xml where contextConfigLocation  is specified.  These two are relevant.  The first location is general to the whole application while the second is specific to the DispatcherServlet scope:

[contextConfigLocation  - application scope](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/web.xml#L35)
[contextConfigLocation - servlet scope](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/WEB-INF/web.xml#L237)

I may very well be wrong (maybe spring mvc requires this), but I don't see why applicationContext-web.xml needs to be scoped to the DispatcherServlet.  One possible solution may be to get applicationContext-web.xml to load after applicationContext-business.xml is loaded by moving applicationContext-web.xml from line 237 to line 35 and put it after applicationContext-business.xml.

**Comment by pvannierop** [comment] 2019-07-02 10:34
@n1zea144 

My knowledge on Spring is not sufficient to solve this issue. What I noticed based on your explanation is that the problem can be located in CacheMapUtil. In CacheMapUtil there is this `@PostConstruct` method:
```
    @PostConstruct
    private void initializeCacheMemory() {
        // CHANGES TO THIS LIST MUST BE PROPAGATED TO 'GlobalProperties'
        this.cacheEnabled = (!authenticate.isEmpty() 
                && !authenticate.equals("false") 
                && !authenticate.equals("social_auth"));
        if (cacheEnabled) {
            LOG.debug("creating cache maps for authorization");
            populateMolecularProfileMap();
            populateSampleListMap();
            populateCancerStudyMap();
        }
    }
```

What strikes me here is that no errors occur when using `-Dauthenticate=false` or `-Dauthenticate=social_auth`. This means that the `if (cacheEnabled) {...}` block with methods that use all kinds of autowired repositories (that depend on applicationContext-business.xml being processed) triggers the error.

When reading the Spring MVC [docs](https://www.baeldung.com/spring-web-contexts) I do not see moving _applicationContext-web.xml_ as the solution (docs do not do this either). I do not understand how the problem may arise since the application context apparently is the parent of the servlet context:

> So far, we’ve seen two major types of contexts: the **root web application context** and the **dispatcher servlet contexts**. Then, we might have a question: are those contexts related?
> 
> It turns out that yes, they are. In fact, the **root context is the parent of every dispatcher servlet context**. Thus, beans defined in the root web application context are visible to each dispatcher servlet context, but not vice versa.
>

**Comment by caaespin** [comment] 2019-07-09 17:09
Hi, can anyone let me know if this ticket will be addressed at the next release? we are unable to upgrade from v 1.18.1 to the latest (>3.0.x) because of this bug. 

What is your time frame? 

thanks!

**Comment by n1zea144** [comment] 2019-07-09 19:00
@pvannierop @oplantalech After spending time in the debugger, what appears to be causing this issue is an interdependency between two MyBatis mappers.  One mapper, [GenesetMapper.xml](https://github.com/cBioPortal/cbioportal/blob/master/persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/GenesetMapper.xml#L62) has a dependency on [GeneMapper.xml](https://github.com/cBioPortal/cbioportal/blob/master/persistence/persistence-mybatis/src/main/resources/org/cbioportal/persistence/mybatis/GeneMapper.xml).  When Geneset mapper is loading, it looks for GeneMapper but cannot find it.  This is the cause of the org.apache.ibatis.builder.IncompleteElementException reported in this PR (its not directly caused by the CacheMapUtil instantiation).

It may be due to luck, but this issue only appears when running the cBioPortal backend via the webapp-runner container.  In light of this, all I can surmise is that Apache Tomcat and webapp-runner manage context differently.

In any event, I have this [ PR 6367](https://github.com/cBioPortal/cbioportal/pull/6367) which fixes the issue (at least on my local machine :-) ).  It directs MyBatis to scan for mappers independent of the scanning and autowiring of repositories.

cc @Sjoerd-van-Hagen @inodb

**Comment by Sjoerd-van-Hagen** [comment] 2019-07-09 23:15
Thanks Ben!

**Comment by pvannierop** [comment] 2019-07-10 06:51
@n1zea144 Thanks a lot for diving into this issue.

**Comment by n1zea144** [comment] 2019-07-10 20:46
Happy to help.  I've seen that @pvannierop has approved the PR, so I'm assuming its fixed on your end too.   Is this true?  Can I merge the PR and close this issue?

**Closed** 2019-07-11 00:34 UTC
Labels: bug
