### ISSUE TITLE
Trouble Importing study_es_0

### ISSUE THREAD

**Issue by bobml** [cBioPortal/cbioportal#2568] opened 2017-06-12 18:01 UTC
I have installed cBioportal locally using 1.6.1 with Schema 2.2, following all the documentation notes. The Study: study_es_0 has been validated then I try the import using:

./metaImport.py -s ../../../test/scripts/test_data/study_es_0/ -n -o

All goes well until it hits the data_fusions.txt file and it throws Java error listed as:
ABORTED!
java.lang.IndexOutOf BoundsException: Index: 0, Size; 0
...
Error occurred during the data loading step. ...

Any thoughts?

**Comment by sandertan** [comment] 2017-06-14 10:12
Hi @bobml ,

Thanks for reporting this issue. It's caused by fusion data which is not imported correctly, and the recent addition of the gene panel datatype. I'm working on a fix in https://github.com/cBioPortal/cbioportal/pull/2506 .

For now, if you rename `meta_fusion.txt` (in `cbioportal/core/src/test/scripts/test_data/study_es_0/`) to `meeta_fusion.txt`, the fusion meta and data files will be skipped, and the import will be succesfull.

Let me know if you run in any more trouble,
Sander

**Comment by sandertan** [comment] 2017-07-18 08:25
Hi @bobml this issue is fixed in the latest 1.7.3 release.

**Closed by sandertan** 2017-07-18 08:25 UTC
Labels: bug
