### ISSUE TITLE
Cancer Types Summary Download PDF: parts of the graph are cut off

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#3213] opened 2017-09-30 13:02 UTC
In the Cancer Types Summary downloaded PDF,  parts of the graph are cut off.

![image](https://user-images.githubusercontent.com/11892704/31045978-170c646c-a5be-11e7-890f-28f83c217692.png)

**Comment by Tamba32** [comment] 2017-10-02 17:20
Fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/646

**Comment by schultzn** [comment] 2017-10-09 18:50
It looks like now we have a really large canvas, with the plot shown in the top left corner. It this by design? Can't the canvas match the size of the graph?

**Comment by jjgao** [comment] 2017-10-09 20:28
I don't think it's by design. @alisman @Tamba32 please look into this?

**Comment by alisman** [comment] 2017-10-10 00:54
@Tamba32 you can see this especially on MSKCC impact result.  See attached PDF.  It should look more like the output of the old site.
[cBioPortalCancerSummary (4).pdf](https://github.com/cBioPortal/cbioportal/files/1370212/cBioPortalCancerSummary.4.pdf)

http://www.cbioportal.org/beta/index.do?session_id=59b2edbe498e5df2e2950b3d&show_samples=false&

**Closed** 2017-10-11 20:00 UTC
Labels: refactoring
