### ISSUE TITLE
Dockerized cbioportal does not work when run with -Dauthenticate=saml to connect with Keycloak Authentication

### ISSUE THREAD

**Issue by BigBallerDan23** [cBioPortal/cbioportal#6392] opened 2019-07-17 14:31 UTC
Hi all,

I have used docker to successfully deploy cbioportal on -p 8081:8080. I am now trying to secure it with Keycloak. So far I have set up Keycloak and can access its admin console on -p 8180:8080. I have modified all the admin settings according to the documentation as well as the saml setting in portal.properties. It is important to note that running cbiokc container did not work using the MySQL:5.7 database from the kcdb container. I tried this with both jboss/keycloak:4.8.3.Final and jboss/keycloak:latest as images but keycloak failed to run. So I ended up running it with the default H2 database. 

For the run cbioportal-container command if I change the Java opts argument -Dauthentication from =noauthsessionservice to =saml, docker perpetually restarts the container and cbioportal is no longer accessible. If I change the flag to =ldap, social_auth_google, openid the containers are stable and the login.jsp screen is accessible at the very least. 

Would appreciate any insight! 

Thanks,

Dan

**Comment by khzhu** [comment] 2019-10-24 19:24
Hi @jjgao , I think @BigBallerDan23 had two problems:
1. get keycloak working with mysql
2. get docker version of portal working with SAML authentication.
nygc's problems was caused by tomcat SSL setting, it is a bit different.

**Comment by jjgao** [comment] 2019-10-25 21:02
@BigBallerDan23 since this has been open for a while (sorry we didn't get back to you earlier), I am going to close this. Please feel free to open if you still have the problem.

**Closed by jjgao** 2019-10-25 21:02 UTC
Labels: docker, question
