### ISSUE TITLE
timeline: starting with the first event

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7018] opened 2020-01-20 21:04 UTC
Currently, we start with the first event when the event time is negative. When the first event is positive, do we always start with 0 or the first event?

This is in prep for support time data with time 0 or birthdate.

**Comment by jjgao** [comment] 2020-03-23 19:21
@inodb I am wondering if this is straightforward? ... thinking of prioritizing it.

**Comment by inodb** [comment] 2020-03-23 19:26
looks indeed like it currently always starts with 0. Shouldn't be too hard to change this to be first event I think. But not sure actually if the zooming takes into account negative start times of the timeline axis (and positive ones as proposed in this issue) CC @Luke-Sikina

**Comment by Luke-Sikina** [comment] 2020-03-23 20:21
Regarding the timeline repo itself, I think we already support timelines with negative start dates. The timeline json I've been testing with starts at -18y and seems to work well. Is it possible that the issue is in the frontend repo instead?

**Comment by inodb** [comment] 2020-03-23 20:40
@Luke-Sikina that's great that negative values work! I wasn't sure whether we had tested that for the zoom feature but turns out we did 👍 

This issue is not so much about the negative values, but rather starting the timeline from the first event. So instead of having the timeline start at "0" it could start at e.g. 32 years as shown above ☝️ in JJ's example. I'll try with that example to see if it works

**Comment by inodb** [comment] 2020-03-23 23:59
This btw looks a lot better with latest version due to improved trimming logic, but will look into starting these from first event:

<img width="1227" alt="Screen Shot 2020-03-23 at 4 50 46 PM" src="https://user-images.githubusercontent.com/1334004/77374283-a910b380-6d40-11ea-90f9-8a365263c36d.png">

**Comment by inodb** [comment] 2020-06-02 14:57
Hmm I'm not sure if it's worth fixing this, b/c we got the new timeline in development 

a quick fix causes this:

![screenshot_timeline.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/1cddf09a-84ae-47bb-ba72-858462b769a6)

So need to change tick style:

![timeline_tick_fixes.png](https://images.zenhubusercontent.com/58337ef1b9dc3c622022519c/2973cb75-e6a2-4ab3-b3e1-e877f32dbb0b)

I could make some fixes to always show full 32y10m for first tick. Let's discuss if we think this is worth pursuing further

**Comment by alisman** [comment] 2020-08-31 14:39
@jjgao We now start with first event like so.    The raw data is indexed from birthdate.  Can we close this?

![image](https://user-images.githubusercontent.com/186521/91732293-0b82a100-eb76-11ea-87d1-71be5c2da433.png)

**Closed** 2020-08-31 18:34 UTC
Labels: discussion, timeline
