### ISSUE TITLE
Duplicate studies in public portal

### ISSUE THREAD

**Issue by Sjoerd-van-Hagen** [cBioPortal/cbioportal#7336] opened 2020-03-27 12:40 UTC
There are two copies of the same studie with a different identifier. Most likely, the identifier got updated on datahub and the study got loaded next to the older version instead of replacing it. These are the studies:
https://www.cbioportal.org/study/summary?id=cfdna_msk_2019
https://www.cbioportal.org/study/summary?id=mixed_cfdna_msk_2019

The first has the download link and still exists in datahub, the second one does not. Probably the second one needs to be removed from the database to fix this issue. @inodb I guess this one is for you?

**Comment by inodb** [comment] 2020-03-27 13:12
Thanks for reporting @Sjoerd-van-Hagen ! @rmadupuri's already on it :)

We have some cron jobs to catch these issues, but i think they're run daily. Not directly post import

**Comment by rmadupuri** [comment] 2020-03-27 16:10
@Sjoerd-van-Hagen @inodb the issue is now fixed. The second study is removed from db.

**Closed by rmadupuri** 2020-03-27 16:10 UTC
