### ISSUE TITLE
new code of customized sample query broke jsp in tomcat 7

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#1535] opened 2016-07-24 02:22 UTC
![image](https://cloud.githubusercontent.com/assets/840895/17081371/a6755938-5123-11e6-8f57-76d5d77bc101.png)

![image](https://cloud.githubusercontent.com/assets/840895/17081376/d6863890-5123-11e6-9cb5-59169b45a776.png)

**Comment by jjgao** [comment] 2016-07-24 02:38
@fedde-s I couldn't find a proper solution, so I revert part of your code in #1536. Please make the proper fix when you have time. Thanks.

**Comment by fedde-s** [comment] 2016-07-25 13:02
I cannot reproduce the error in Tomcat 7.0.70 as packaged in https://hub.docker.com/_/tomcat/ , either under JDK 8u91 and JDK 7u101.

**Comment by jjgao** [comment] 2016-07-25 14:21
That's strange. Maybe it's not related to tomcat 7. It worked on Heroku too, but did not on either our server or my Mac.

**Comment by fedde-s** [comment] 2016-08-25 12:10
Since @jjgao merged the pull request into the hotfix branch over a week ago and I have heard no further complaints, I will assume that the issue has been solved. If not, please do re-open it.

**Closed by fedde-s** 2016-08-25 12:10 UTC
Labels: bug, critical, hotfix
