### ISSUE TITLE
Let the import process generate the standard case lists

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal#494] opened 2015-11-17 10:18 UTC
Let the import process generate the standard case lists based on the data loaded. For example: if the study loaded contains CNA and mRNA (microarray) data, then the import process should generate the case lists `<study_id>_all`, `<study_id>_cna` and `<study_id>_mrna`. 

This replaces the need for manually providing the import process with these files (see [documentation of Case lists files](https://github.com/cBioPortal/cbioportal/blob/v1.8.2/docs/File-Formats.md#case-lists) for a description of the current process). 

Goals: 
- make case lists optional. Users only provide input files for _custom_ case lists. 
- simplify the import process making it much less error prone

**Comment by pieterlukasse** [comment] 2015-11-17 11:23
Question1: how to generate "All Complete Tumors" in the case where we have more than 1 data sets for a same genetic profile (e.g. multiple mRNA datasets for mRNA genetic profile)?

Question2: should we generate case lists for all possible combinations of two specific experiments? E.g. CNA + mRNA(RNAseq),  or CNA + mRNA(microarray)

**Comment by pieterlukasse** [comment] 2016-02-05 15:46
@ecerami : I will be very happy if we can work on this one in next phase ;)

**Comment by ecerami** [comment] 2016-02-05 18:34
@pieterlukasse:  this is actually a little trickier than it looks :-)  The problem is that if we have a MAF file, and generate a case set of sequenced samples from that MAF file, it's very possible (especially for targeted sequenced panels), that we have many samples that are Wildtype for all genes sequenced.  We therefore need a separate case list to specify all samples sequenced, including the Wildtype cases.

**Comment by pieterlukasse** [comment] 2016-02-05 19:12
@ecerami : did you mean "excluding the wildtype cases"  in you last sentence?

**Comment by ecerami** [comment] 2016-02-05 19:16
@pieterlukasse:  no, I mean "including WT cases", e.g. if we have sequenced 100 samples, and 10 are WT, we need a list of 100, not 90.

**Comment by Sjoerd-van-Hagen** [comment] 2016-02-11 11:52
@ecerami Can we expect a file that lists all the sequenced samples, or all samples that are sequenced but are wild-type?

**Comment by fedde-s** [comment] 2016-02-11 12:02
@Sjoerd-van-Hagen I think changing the requirements that way would only make it needlessly complex both for the users and for the software, no need to manually figure out which of the sequenced samples are not in the MAF file, only to have cBioPortal make a full list of all sequenced samples again.

**Comment by pieterlukasse** [comment] 2016-02-11 12:06
@fedde-s , @Sjoerd-van-Hagen   : i discussed it with Ethan in more detail before. I will add the updated information.

**Comment by zheins** [comment] 2016-02-12 16:18
@pieterlukasse We deal with this issue in our pipelines by appending sequenced samples as a comment line to the top of the MAF.

**Comment by fedde-s** [comment] 2016-02-12 16:23
@zheins As you initially wrote the validation script, this comment also included control samples used in the Matched_Norm_Sample column. I believe @pieterlukasse moved this list to an optional field in the corresponding metadata file, as an actual valid MAF file would start with a comment declaring the version number of the MAF format used.

**Comment by zheins** [comment] 2016-02-12 19:03
That works too, you can use that field to get the correct numbers samples for the case lists.

**Comment by fedde-s** [comment] 2016-02-12 19:16
In that case it might make sense to get rid of separate files for such case lists for *all* molecular data types, and simply include the sample lists in the corresponding metadata file.

**Comment by pieterlukasse** [comment] 2016-02-17 10:30
@zheins, @fedde-s : I like the idea of having a field for this in the meta file. It also is a good step in the direction of solving the current issue where case lists are indirectly linked to genetic profiles via (part of) their stable_id. 
@ecerami, @n1zea144 : what do you think?

**Comment by pieterlukasse** [comment] 2016-02-26 11:18
Update: I also found some code in `org.mskcc.cbio.portal.model.AnnotatedPatientSets`  that tries to define the default case list based on a new field added to the case lists: `case_list_category` with all possible categories listed in the enum `org.mskcc.cbio.portal.model.PatientListCategory`. This is actually used in some places like `CrossCancerJSON` and `CrossCancerMutationDataServlet` (but I think other places, like the query page, are still using the old way via stable_id substrings). @ecerami : is this perhaps an alternative solution?

**Comment by fedde-s** [comment] 2016-05-17 08:39
@pieterlukasse addressed this as part of #798, specifically commit c6e5978417871f75b76c100c0c0c2e26339ed288, which has been merged into the release candidate. Is this still an issue?

**Comment by pieterlukasse** [comment] 2016-05-23 14:32
solution indicated by @fedde-s is indeed good for now. 

But I still would like to have answers on my questions in my last two comments:
https://github.com/cBioPortal/cbioportal/issues/494#issuecomment-185142883
https://github.com/cBioPortal/cbioportal/issues/494#issuecomment-189227247
@ecerami, @n1zea144 :point_up_2:

**Comment by jjgao** [comment] 2018-05-14 21:04
@pieterlukasse would you like to keep this open? It's being `in progress` for so long :)

**Comment by sandertan** [comment] 2018-08-16 09:59
This would be nice to have. For all profiles that have samples in the columns (all types of cna, all types of expression, methylation, all types of protein quantifications), it would be nice to autogenerate the case list. This will make it a lot easier to get staging files in the correct format and will lower the risk of making errors.

Only for mutations files the separate case list is required. And perhaps for fusion events, but those are currently added to the mutation profile.

**Comment by fedde-s** [comment] 2018-08-16 14:27
> naming of `_sequenced` can be improved by refactoring it to `_mutations`

I want to argue that that's not just a refactoring, it's a change in an external interface depended on by data transformation code and many existing archived studies. But if you do feel it would would be worth the effort, I'd suggest deprecating `_sequenced` in favour of the new convention.

**Comment by jjgao** [comment] 2018-08-16 15:30
It would be nice to rename it to `_mutations` but I agree with @fedde-s that it's probably not worth the effort. Especially we still plan to [redesign the case list](https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit) - not a high priority currently but I hope we can get to it at some point.

**Comment by sandertan** [comment] 2019-03-06 13:55
Proposal of JJ in RFC37: https://docs.google.com/document/d/1aBbkTAFv5nCqBv66BOgwvlt5kymgt0lQ7l_pqaFrupc/edit

**Closed** 2019-07-20 16:11 UTC
Labels: cleanup, enhancement, hyve, pipeline

**Comment by Sjoerd-van-Hagen** [comment] 2019-08-07 12:43
@jjgao is this implemented, or just made part of the design of future implementation work?
