### ISSUE TITLE
Improve caching cbioportal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#4465] opened 2018-07-16 22:00 UTC
Current cache increases with each unique sample combination

Mybatis only allows to set number of object not size

**Comment by jjgao** [comment] 2018-07-17 03:10
The internal portals are still going down from time to time. We turned off mybatis caching completely in the public portal, but couldn't do that for the private portal since it would significantly impact the performance.

I remember @n1zea144 or @ersinciftci mentioned there was some way to cache per sample / gene, instead of per query (set of sampels, set of genes).

**Comment by n1zea144** [comment] 2018-07-17 13:34
@jjgao  Timely message.  I understand from @zhx828 that the built-in Mybatis cache is not working as expected.  I thought I would look into using Ehcache (hibernate cache system) with MyBatis.  For one, its widely used and we've used it in other projects.  Also, there are tools available to monitor the cache.  This will allow us to confirm the expected behavior based on our settings.

**Comment by n1zea144** [comment] 2018-07-18 19:31
@jjgao Actually, I'm not set on using Ehcache yet.  After some further investigation, it looks like we can implement our own custom cache.  I think its more important to pursue this route as the structure of keys/values in the cache created by the MyBatis cache implementation is not ideal for our use-cases.  As a start I'm going to implement a custom cache which simply proxies the MyBatis cache implementation but also logs the key/values just to confirm our suspicions (I'll make this available on a dev server).

If this confirms our suspicions, we will then have the flexibility to implement our custom cache from scratch or utilizing Ehcache or even REDIS.

**Comment by n1zea144** [comment] 2018-07-19 19:37
@jjgao @ersinciftci @inodb @zhx828 @sheridancbio I now have a custom cache implementation in place.  It does confirm that keys are generated for each namespace/query/parameter list (see attached).  In fact, MyBatis has defined a CacheKey type and a reference to an instance of this is stored in the cache, which ultimately in the MyBatis library is just a HashMap (depending on eviction method, there is a different decorator class). Based on my observation, the slightest change in the query does result in a different cache key.

I see a few options going forward:

- Since we are already invested in MyBatis, we can build out a custom MyBatis cache implementation along the lines of what I have just done and organize cache memory that is tuned to our use cases.  We would then intercept calls to cache.put/get and translate those calls based on the organization of the cache.  In this scenario, we have the ability to use an existing MyBatis cache implementation (like LruCache), roll our own, our even bring in Hibernate or REDIS.  The benefit of this would be all the cache code could be centralized.  Also, we could tune the cache based on the namespace we are supporting.
- We turn off MyBatis cache completely, implement our own cache system (could be based on Hibernate or REDIS) and intercept calls somewhere in our middleware.  If we did this, we would have to add caching code at multiple points in the middleware.  We may want to consider this option if we feel there is a chance we will move away from MyBatis in the future.

In either scenario, we have to figure out what the cache organization should be - i.e., study-sample, study-patient, study-patient-sample.

I think this is worthy of a discussion to figure out next steps.

Debugger screen capture of a MyBatis cache key during a cache.put operation.
![image](https://user-images.githubusercontent.com/366003/42964635-9f29fed0-8b65-11e8-94d0-23913d9835b7.png)

**Comment by n1zea144** [comment] 2018-07-20 19:40
@jjgao We will take this task on in the pipeline scrum The week of July 30 (many of us our out of the lab next week).  It would be helpful if you can prioritize the endpoints that require addressing.  Happy to discuss further in the lab.

**Comment by jjgao** [comment] 2018-07-23 15:50
@n1zea144 thanks for the analysis! Happy to discuss further.

**Comment by jjgao** [comment] 2018-11-05 17:51
I am looking into this and see if we can turn off caching for private portals. 

We have turned it off for public portal, but when turning it off for private portals, they become very slow.

**Comment by jjgao** [comment] 2019-06-12 21:10
@n1zea144 I am closing this one. Please create separate issues for caching improvement you are working on.

**Closed by jjgao** 2019-06-12 21:10 UTC
Labels: bug, critical, priority
