### ISSUE TITLE
Unable to download Oncoprint from chrome

### ISSUE THREAD

**Issue by kalletlak** [cBioPortal/cbioportal#4038] opened 2018-03-28 19:58 UTC
and PDF format in any browser

**Comment by jjgao** [comment] 2018-03-29 19:20
@kalletlak I couldn't reproduce it? Is it on the production portal?

**Comment by adamabeshouse** [comment] 2018-04-06 21:16
I can't reproduce this, but could it have to do with an ad blocker or popup blocker you have installed, preventing the download action?

**Comment by jjgao** [comment] 2018-04-09 19:57
@kalletlak I am closing this since we cannot reproduce it.

**Closed by jjgao** 2018-04-09 19:57 UTC
