### ISSUE TITLE
Web layer build error due to deprecation of repo.spring.io

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#8481] opened 2021-03-31 14:18 UTC
A user has reported the failure to build the web layer which appears to be due to unauthorized access to the repos above.  Not user why only this user has this issue.  This looks like it could affect our session service codebase too.

https://groups.google.com/g/cbioportal/c/2TzLJ7h9UAQ

**Comment by kalletlak** [comment] 2021-03-31 18:26
Unable to reproduce it. User might be using older version of the portal. Closing it for now.

**Closed by kalletlak** 2021-03-31 18:26 UTC
