### ISSUE TITLE
Defined cases are deselected/reset when gene set is updated in the modify query view (Beta Portal) 

### ISSUE THREAD

**Issue by walidchatila** [cBioPortal/cbioportal#2540] opened 2017-06-06 16:17 UTC
The list of user defined cases , selected using the study view, are deselected when updating/adding genes used in a query.  This forces the user to reselect a new set of cases. 

![image](https://user-images.githubusercontent.com/6421902/26839684-c430aa30-4ab1-11e7-9b4f-86172fca753e.png)

![image](https://user-images.githubusercontent.com/6421902/26839696-ce85ad64-4ab1-11e7-910c-1879d7dc5e45.png)

**Comment by alisman** [comment] 2017-06-12 17:48
@adamabeshouse lets discuss this when you get a sec

**Comment by adamabeshouse** [comment] 2017-06-14 17:51
seems to be fixed by new work, can't reproduce

**Closed by adamabeshouse** 2017-06-14 17:51 UTC
Labels: refactoring
