### ISSUE TITLE
Custom driver annotation does not work

### ISSUE THREAD

**Issue by RJWANGbioinfo** [cBioPortal/cbioportal#7616] opened 2020-06-15 03:51 UTC
Hi,

It seems the custom driver annotations can not work properly in the cBioPortal docker.
The driver annotation and tier annotation can be displayed in the annotation data panel, but none of them can be selected or unselected (see the attached screenshot). Could you help me to figure out how to fix it? Thanks in advance!

I didn't find any error in `docker logs "cbioportal-container" `

The error log in the chrome developer mode:
`mobx.module.js:2461 Uncaught Error: [mobx] Invariant failed: [ComputedValue 'ObservableObject@3725.customBinary'] It is not possible to assign a new value to a computed value.
    at re (mobx.module.js:2461)
    at t.set (mobx.module.js:1577)
    at Object.set (mobx.module.js:1789)
    at Object.<anonymous> (7.af24470d5293dfbbf991.chunk.js:161)
    at F (mobx.module.js:911)
    at Object.n [as onSelectCustomDriverAnnotationBinary] (mobx.module.js:902)
    at t.value (7.af24470d5293dfbbf991.chunk.js:161)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at h (react-dom.production.min.js:15)
    at react-dom.production.min.js:15`

![image](https://user-images.githubusercontent.com/51307984/84616279-8dc5c800-ae99-11ea-9823-2a1a82ddc641.png)

![image](https://user-images.githubusercontent.com/51307984/84616337-b6e65880-ae99-11ea-8c5b-d224dd450f41.png)

**Comment by jjgao** [comment] 2020-06-15 14:18
@pvannierop @Sjoerd-van-Hagen any insights?

**Comment by pvannierop** [comment] 2020-06-15 18:42
@RJWANGbioinfo Thank you for this bug report. I will try to reproduce this issue asap and provide a fix if needed.

**Comment by pvannierop** [comment] 2020-06-22 08:56
@RJWANGbioinfo @jjgao @Sjoerd-van-Hagen I have filed a PR that fixes this issue.

**Comment by RJWANGbioinfo** [comment] 2020-06-22 14:04
@pvannierop Thanks for your update!
Just a quick question on it:

Since I'm using the cBioPortal Docker, to fix this bug, I need to map the updated files (custom-driver-annotations.spec.js; ResultsViewPageStore.ts; DriverAnnotationControls.tsx) to the docker, am I right?

If so, could you let me know the path of these files in the docker? I didn't find the corresponding folder (e.g., src/pages/resultsView/) in the docker containing these files.

Thank you!

**Comment by pvannierop** [comment] 2020-06-24 09:51
@RJWANGbioinfo I do not precisely know your setup, but the normal way would be to:
1. wait for the PR to be accepted in the master branch
2. wait for a new release of cbioportal to be announced that includes this fix
3. redeploy with Docker.

I assume here that you use the `cbioportal/cbioportal:latest` image from dockerhub. If so, all you need to do is wait for the next release to be announced after merge. However, the PR has not been merged yet because of failing tests not related to this PR.

**Comment by RJWANGbioinfo** [comment] 2020-06-25 04:09
@pvannierop Thanks for letting me know! 
I'll wait for the next release.

Thank you!

**Closed** 2020-08-18 19:17 UTC
