### ISSUE TITLE
Problem with CNV data

### ISSUE THREAD

**Issue by ChandraPedamallu** [cBioPortal/cbioportal#1841] opened 2016-10-24 20:47 UTC
Hi,

We noticed that in DREAM data set in Prostate cancer, the copy number calls looks randomly to annotate them AMP or DEL.

Could you please kindly check the PPT file attached?

We greatly appreciate if you can kindly provide some insights on it.

Thank you

Best
Chandra
[cBioPortal_CNV_problems.pptx](https://github.com/cBioPortal/cbioportal/files/548982/cBioPortal_CNV_problems.pptx)

**Comment by pieterlukasse** [comment] 2016-10-25 08:55
@sandertan can you dive into this one? Would be good to check if the CNA algorithm used could be the cause of this or if the issue is likely at some other step of the pipeline.

**Comment by sandertan** [comment] 2016-10-26 14:05
Dear Chandra,

If I understand your question correctly, you're wondering why the same log2 value is called differently for different samples. This is indeed an interesting question, and also viewable when 1 gene is selected in cBioPortal, for example:

![cbioportal_example](https://cloud.githubusercontent.com/assets/9624990/19728051/3e0c3290-9b92-11e6-9c0c-ebba23bc4166.png)

We see for certain log2 values a deep deletion is called, while for some lower log2 values, diploid is called. I've reproduced your results using the staging files (`data_log2CNA.txt` and `data_CNA.txt`, downloaded [from datahub](https://github.com/cBioPortal/datahub/blob/master/public/prad_su2c_2015.tar.gz):

![plot_study](https://cloud.githubusercontent.com/assets/9624990/19728086/5ac3c5e2-9b92-11e6-9223-4b3dcfda3380.png)

To make sure there aren't any errors in our pipeline, I've rerun the copy number calling algorithm :
![plot_sander](https://cloud.githubusercontent.com/assets/9624990/19728098/646533f6-9b92-11e6-8f6c-b77be169974c.png)

The result is similar. The curves are slightly different, probably because I used a slightly smaller gene-list and ran a different version of Gistic with default parameters. I noticed that both the log2 values and the copynumber calls are output from Gistic, and are included in the gzip from datahub (`all_data_by_genes.txt` and `all_thresholded.by_genes.txt`)

The overlap in calls for similar log2 values has to do with the way the copy number alterations are called by Gistic 2.0. In the documentation of Gistic, the authors state there are a number of important factors taken into account for the copy number calling, such as:
1. Number of basepairs of the event
2. Amplitude of the event
3. Location of the event (chromosome arm, intergenic)

Gistic then defines for example:
1. Location of the peak of the event
2. Significance of the peak
3. Scoring of the peak
4. Overlap genes with peaks

In the paper the authors describe a case where a gene contains multiple non-overlapping deleted markers with different scores. My understanding of it is, to make the best call, a number of (sample specific) variables are taken into account which result in a different call compared to when for example the call is done solely on the mean log2 of the markers.

A summary of the method can be found in the documentation: ftp://ftp.broadinstitute.org/pub/GISTIC2.0/GISTICDocumentation_standalone.htm and the full method can be read [in the paper](http://genomebiology.biomedcentral.com/articles/10.1186/gb-2011-12-4-r41).

I hope this helped to explain your observation. If you have any more questions, don't hesitate to contact us.

Sander

**Comment by sandertan** [comment] 2017-06-22 08:28
Hi @ChandraPedamallu I'll close this issue for now. If you would like to discuss this topic some more, please reopen it.

**Closed by sandertan** 2017-06-22 08:28 UTC
