### ISSUE TITLE
HRRS filter PR breaks cbioportal deployment

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/cbioportal#6377] opened 2019-07-11 15:01 UTC
Fix for bug caused by https://github.com/cBioPortal/cbioportal/pull/5806/files.

The recent implementation of HRRS filter introduced new portal.properties params that are mandatory to set. 
```
# enable/disable hrrs logging
# filter which logs incoming web requests to specified logging directory
# logs must be decrypted for more in-depth information
hrrs.logging.filepath=
hrrs.enable.logging=
```
If not set, the portal throws an error and terminates. 

1. It would be better to define default values for both params so the portal always runs.
2. When setting `hrrs.enable.logging=false` the property `hrrs.logging.filepath` is still required. The implementation better not require `hrrs.logging.filepath` to be set, when not logging.

P.S. I wrote this is a hurry. Please excuse my terseness.

**Comment by inodb** [comment] 2019-07-11 15:02
Seems like duplicate of: https://github.com/cBioPortal/cbioportal/issues/6368

**Comment by inodb** [comment] 2019-07-11 15:03
GitHub gives recommended similar issues btw:

<img width="668" alt="Screen Shot 2019-07-11 at 11 02 46 AM" src="https://user-images.githubusercontent.com/1334004/61062052-7ea5e280-a3cb-11e9-945e-ed128c180a1e.png">

**Comment by pvannierop** [comment] 2019-07-11 16:14
@Ino ah ha ha thnx

**Closed** 2019-10-24 19:14 UTC
Labels: bug, duplicate, hotfix
