### ISSUE TITLE
using `-Dehcache.cache_type=hybrid` throws error

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6712] opened 2019-10-16 11:20 UTC
Getting this error when using `-Dehcache.cache_type=hybrid`:

```
: Provider org.redisson.jcache.JCachingProvider not a subtype                                                                                               
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:479)             
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)                                          
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)                       
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)                                            
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)                                              
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:237)     
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:703)                   
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)                                      
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)                                   
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)                                                  
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)                                         
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)                                                                
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5278)                                                                
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)                                                                             
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)                                                                  
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)                                                                  
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                         
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                  
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                  
        at java.lang.Thread.run(Thread.java:748)                                                                                                            
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.config.internalTransactio
nAdvisor': Cannot resolve reference to bean 'org.springframework.transaction.annotat
```

It works fine when using disk only with `-Dehcache.cache_type=disk`

**Comment by sheridancbio** [comment] 2019-10-23 16:35
I have commented on this via slack. We believe the problem is due to disk resource limits not being larger than heap resource limits (as the Ehcache cache manager requires). A PR was merged recently which detected and reported such errors in the logs (#6715).
We plan to redeploy kubernetes public portals this week with adjusted resource limits and see if that corrects this problem completely.

**Comment by sheridancbio** [comment] 2019-10-23 18:31
Adjustment of disk usage limit properties to be larger than heap usage limit properties allowed the public portal to be successfully redeployed under kubernetes with cache_type hybrid.  So this appears to not require and code fixes.

**Closed by sheridancbio** 2019-10-23 18:31 UTC
Labels: backend, bug
