### ISSUE TITLE
All Knwoledgebase logos to got together

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/cbioportal#2838] opened 2017-07-24 22:36 UTC
I thought this was decided in the group meeting to have OncoKB, my cancer genome and Civic together. 
![screen shot 2017-07-24 at 6 23 43 pm](https://user-images.githubusercontent.com/12007862/28547867-f0eba9e0-709e-11e7-80dc-24cfa65dd3dd.png)

**Comment by inodb** [comment] 2017-07-24 22:40
Thanks @ritikakundra . Duplicate of #2812

**Closed** 2017-07-27 18:47 UTC
Labels: duplicate, refactoring
