### ISSUE TITLE
forwarding page is wrong after log in

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7386] opened 2020-04-12 20:37 UTC
How to reproduce:
- Signout of MSK Portal if logged in
- Open https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&case_id=P-0002181
- It redirects to https://cbioportal.mskcc.org/api/studies/mskimpact

**Comment by alisman** [comment] 2020-04-27 16:03
@n1zea144 it seems we need to change saml.logout.local to false to fix this.  Does that make sense?

**Comment by n1zea144** [comment] 2020-04-28 00:24
@jjgao @alisman local/global logout really comes into play when you when we want it so the user logs out of all apps/sessions created within the MSK SAML server or only logout the local/cBioSession.  As the logout screen shows, technically the termination of the session is not complete until the browser is closed (chrome is exited).  Putting the close browser issue aside for the moment, it does look like there is an issue with how forwarding is currently implemented after sign on - try this experiment -

- Signout of MSK Portal if logged in
- Terminate Chrome browser process
- Open https://cbioportal.mskcc.org/case.do?cancer_study_id=mskimpact&case_id=P-0002181

You will see that you will get redirected to the SAML server login page and after successful authentication, your browser URL lands on https://cbioportal.mskcc.org/api/studies/mskimpact, but the page looks to be JSON for the mskimpact study.

Sometime ago, we changed the security configuration to allow unauthenticated requests to /case.do and /patient and let the frontend handle the routing of those requests:

`<intercept-url pattern="/case.do*" access="permitAll"/>`
`<intercept-url pattern="/patient*" access="permitAll"/>`

so I'm not sure what the frontend does in the scenario described by this ticket.  The fact that during the exercise I described above, I am redirected to a SAML login page makes me believe that the frontend is making a request to a protected endpoint.

I have to check, but I imagine I would be able to recreate this issue with Google authentication (which would make it slightly easier to debug).  I'll have to dig into this further tomorrow.

**Comment by alisman** [comment] 2020-04-28 14:10
@n1zea144 i will look into exactly what frontend is doing in the scenario described. 

But the fact that the browser needs to be closed to complete the logout doesn't seem like the right behavior.  Is there a reason for that?

**Comment by alisman** [comment] 2020-04-29 17:19
@n1zea144 so, yeah, at some point we decided to handle redirection to logout page in frontend (at least on patient page).  I think the reason was that restoring the user's target URL wasn't working for this page.  Perhaps when there was a very long string of patient ids in url hash for (cohort mode).    I built a system for keeping the target url in local storage and then sending user to login page with a key for that target.  We have a route called /restore which handles this. 

So, what happens on fronted is that any time i detect a 401 response on any api request, we redirect user to the following:

https://cbioportal.mskcc.org?spring-security-redirect=https%3A%2F%2Fcbioportal.mskcc.org%2Frestore%3Fkey%3Dredirect711211765827

It's in various machinations AFTER this that things get screwed up.  A call to some SSO address is what finally redirects user to the json response.  It's not clear to me why it decides to do that. There a few other 302s a long the way.

So, is it possible the above logout url is not valid anymore?

**Comment by n1zea144** [comment] 2020-05-01 15:25
I think you mean "we decided to handle redirection to the login page in frontend"....?

As mentioned to @alisman offline, I've never used that spring-security-redirect endpoint before, so I'm not sure what spring-security is doing with it.   I will have to investigate it further.  Unfortunately, we don't have a dev environment setup to work with the MSK SAML server (only beta and production), so if I have to trace through this, I will have to do it after hours.

I also tried to no avail to get local logout working without closing a browser.  I ended up updating portal.properties for global logout which eliminates the need to close the browser (not sure why that is the case), but as suspected, the forwarding page issue still persists.

**Comment by n1zea144** [comment] 2020-05-01 15:48
Just an update, I discovered that spring-security-redirect is [custom code](https://github.com/cBioPortal/cbioportal/commits/master/security/security-spring/src/main/java/org/cbioportal/security/spring/PortalSavedRequestAwareAuthenticationSuccessHandler.java) we wrote.  Will be looking closer at it....

**Comment by n1zea144** [comment] 2020-05-05 18:40
For the record - 
- Debugging this in a load-balanced production environment is tedious and disruptive, so I tried to debug this in a dev environment using [OneLogin](onelogin.com) as an IDP with a local tomcat.  Unfortunately, I could not reproduce the error.  Which leads me to believe this is something specific to the production environment
- From what I can tell during some after hours debugging of the production environment, the redirect in the study view happens when [savedRequest==null](https://github.com/cBioPortal/cbioportal/blob/master/security/security-spring/src/main/java/org/cbioportal/security/spring/PortalSavedRequestAwareAuthenticationSuccessHandler.java#L89).

Since this issue does not occur in a dev environment and is inconsistent in production (if you logout and visit the link above, sometimes you do get to the patient page) I wonder if this issue has to do with simultaneous user logins not properly handled or something with the tomcat session being shared between two servers.

**Closed** 2020-05-14 23:52 UTC
Labels: bug, critical, priority
