### ISSUE TITLE
too long cross cancer queries give URL too long error

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal#2674] opened 2017-06-28 22:44 UTC

**Comment by ecerami** [comment] 2017-07-05 13:48
@adamabeshouse:  can you please provide an example or URL?

**Comment by alisman** [comment] 2017-07-05 17:12
Hey Adam, if you could add more detail and proposed solution that would help.  I seem to remember this would require endpoint accepting posted data, right?

**Comment by adamabeshouse** [comment] 2017-07-05 18:11
this is a browser-specific issue, only present in browsers with a URL limit, such as internet explorer. This is as opposed to the issue solved by using POST, which is a server-side issue.

**Comment by adamabeshouse** [comment] 2017-07-06 01:14
https://github.com/cBioPortal/cbioportal-frontend/pull/450
https://github.com/cBioPortal/cbioportal/pull/2701

**Comment by adamabeshouse** [comment] 2017-07-06 20:57
@sheridancbio we can't seem to reproduce this in IE11 - are you still seeing this issue?

**Comment by sheridancbio** [comment] 2017-07-11 13:32
I've just run the same cross-cancer query on the latest hotfix release (1.7.3-SNAPSHOT) and it seems to be fixed.
<img width="832" alt="cc_succes" src="https://user-images.githubusercontent.com/7747489/28070650-af0898cc-661b-11e7-923c-1fff5345273c.png">

The original issue was generated in chrome v59.x

**Comment by inodb** [comment] 2017-07-11 15:08
@sheridancbio  I wasn't able to reproduce this bug either. @adamabeshouse what do you think? Should we still merge your PR? I guess theoretically there is still a limit to the hash params

**Comment by adamabeshouse** [comment] 2017-07-11 18:41
I'd say let's just leave it be because the virtual cohort work I'm going to merge soon does away with this entire endpoint (cross_cancer.do) anyway.

**Comment by inodb** [comment] 2017-07-11 18:48
@adamabeshouse sounds good, closing this then, thanks!

**Closed by inodb** 2017-07-11 18:48 UTC
Labels: fixed by pending PR, refactoring
