### ISSUE TITLE
pathway mapper - bad characters

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#7250] opened 2020-02-28 21:16 UTC
![image](https://user-images.githubusercontent.com/10508276/75587845-657aa080-5a45-11ea-87c0-4409e32a3a60.png)

![image](https://user-images.githubusercontent.com/10508276/75587873-74f9e980-5a45-11ea-91c6-70ceae86d1a1.png)
(The "Loading..." pop-up also has this problem but it's hard to capture a screenshot of that one)

**Comment by onursumer** [comment] 2020-02-28 23:01
@tmazor I cannot reproduce this with https://deploy-preview-3037--cbioportalfrontend.netlify.com/. which browser are you testing on?

**Comment by ugurdogrusoz** [comment] 2020-02-29 06:39
I don't see any such characters either. Please report your platform and steps to reproduce.

**Comment by tmazor** [comment] 2020-03-02 19:00
This is an funny one... when I use the link @onursumer provided above, I also can't reproduce it.

But if I instead go to cbioportal.org and use the bookmarklet @alisman provided on slack to enter a PR #, that's when I can reproduce this issue.

So perhaps this is an artifact of whatever magic that bookmarklet does? Which is the more accurate representation of how this will behave when deployed?

**Comment by onursumer** [comment] 2020-03-03 16:46
Fixed by #7256

**Closed** 2020-03-03 18:29 UTC
Labels: frontend, pathwaymapper

**Comment by tmazor** [comment] 2020-03-03 18:35
Looks good!
