### ISSUE TITLE
500 error on clinical data bin counts endpoint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7240] opened 2020-02-26 16:24 UTC
Endpoint:
api/clinical-data-bin-counts/fetch?dataBinMethod=STATIC

Because it's a post method, Loggly can't tell us what was submitted.

Error occurs after some unknown interaction with study page, e.g:
https://www.cbioportal.org/study/summary?id=breast_msk_2018%2Cbrca_tcga_pan_can_atlas_2018%2Cbrca_mbcproject_wagle_2017%2Cbrca_mskcc_2019%2Cccle_broad_2019%2Cmixed_allen_2018%2Ctmb_mskcc_2018

**Comment by kalletlak** [comment] 2020-04-06 19:34
unable to reproduce it and there is no much information about the attribute (chart). Closing it for now.

**Closed by kalletlak** 2020-04-06 19:34 UTC
Labels: api-error, priority
