### ISSUE TITLE
Gene sets in plots tab keeps showing loading icon when not querying gene set

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#6139] opened 2019-05-23 19:25 UTC
https://beta.cbioportal.org/results/plots?Action=Submit&cancer_study_list=gbm_tcga&case_set_id=gbm_tcga_all&clinicallist=NUM_SAMPLES_PER_PATIENT%2CPROFILED_IN_gbm_tcga_mutations%2CPROFILED_IN_gbm_tcga_gistic&gene_list=TP53&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&show_samples=false&tab_index=tab_visualize

![Screen Shot 2019-05-23 at 3 19 36 PM](https://user-images.githubusercontent.com/1334004/58280445-9ddea700-7d6e-11e9-84a1-74160ae6c8d3.png)

![Screen Shot 2019-05-23 at 3 23 40 PM](https://user-images.githubusercontent.com/1334004/58280528-cebedc00-7d6e-11e9-8dbf-1c47fb5f73e9.png)

Does work when querying gene set list:

https://beta.cbioportal.org/results/coexpression?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=gbm_tcga&case_set_id=gbm_tcga_cnaseq&data_priority=0&gene_list=TP53&geneset_list=VERHAAK_GLIOBLASTOMA_PRONEURAL&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=gbm_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_mutations&tab_index=tab_visualize

![Screen Shot 2019-05-23 at 3 22 09 PM](https://user-images.githubusercontent.com/1334004/58280465-a7680f00-7d6e-11e9-965b-f3656eda4645.png)

Maybe when:

`show_profile_in_analysis_tab: false`

it shouldn't show up in the plots tab?

https://github.com/cBioPortal/datahub/blob/master/public/gbm_tcga/meta_gsva_scores.txt

**Comment by jjgao** [comment] 2019-05-24 21:12
@Sjoerd-van-Hagen @oplantalech maybe we should have a setting in portal.properties or frontend config to turn on GSVA features (off by default)? That way, we can set `show_profile_in_analysis_tab` to `true` so that we will be able to use the data for screenshot tests and at the same time they will not show up in the public portal.

Would you please prioritize this since it's already in production? Please let me know if it'll take some time -- in that case, we may want to remove the GSVA data from the production database temporarily.

**Comment by jjgao** [comment] 2019-05-24 21:13
@oplantalech please send pr to master.

**Comment by jjgao** [comment] 2019-05-24 21:14
@oplantalech you may want to sent pr to master since it's broken in production.

**Comment by Sjoerd-van-Hagen** [comment] 2019-05-24 21:23
@jjgao I was actually thinking that now we have a simplified query page for the non-technical users, perhaps we can now include the GSVA on the query page. It is only one checkbox after all, and only when clicked it will show the additional components to select genesets. Currently, the only way to look at the genesets in the public portal is to copy paste them to the URL, which is clearly not ideal. We would only need to adjust the study file to make this happen.

Imo the GSVA functionality is useful enough to warrant the extra checkbox. @cBioPortal/product what are your thoughts on this?

Regardless of the outcome of the discussion, this here is a bug that should be fixed because it is wrong the genesets in the plots tab if there are not selected in the query page, switch or no switch.

**Comment by jjgao** [comment] 2019-05-24 22:17
Thanks, @Sjoerd-van-Hagen. It may be worth another discussion on Friday call about the interface and plan on gsva. We would also need to have more data e.g on tcga pancan studies in order to turn this one for public portal.

**Comment by Sjoerd-van-Hagen** [comment] 2019-05-27 13:09
@jjgao for PanCan we would first need the expression data, but yes, if we have that we can compute scores for every study.

Perhaps we can enable the GSVA check box on the query page on beta, so @cBioPortal/product can test how it works?

**Comment by jjgao** [comment] 2019-05-28 17:59
@Sjoerd-van-Hagen good idea! Could you help prioritize adding a setting in portal.properties or frontend config to turn on GSVA features (off by default)? It would solve this issue here and allow us to turn it on in beta (and screenshot testing) without changing the metafiles. After releasing 3.0, we can get more feedback on GSVA from others.

**Comment by Sjoerd-van-Hagen** [comment] 2019-05-28 19:03
Right, because both beta and the main portal feed of the same database... forgot about that.

Tbh I do not see this fitting into this week. We have a public holiday on Thursday and a lot of work. I will see what I can do.

**Comment by jjgao** [comment] 2019-05-28 21:24
@Sjoerd-van-Hagen thanks! It's not a blocker for 3.0 because it's already out there in the production. I'll ask @cbioportalpipelines to remove the data for now and we can bring it back once the issue is fixed.

**Comment by jjgao** [comment] 2019-05-28 23:51
@rmadupuri will remove the data files.

**Closed** 2019-09-18 12:43 UTC
Labels: bug

**Comment by Sjoerd-van-Hagen** [comment] 2019-09-18 13:02
@jjgao can we now put the data back?

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-15 11:03
@jjgao see above

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-17 17:50
@jjgao Why do you want to turn off the feature? It is useful and it works.

**Comment by jjgao** [comment] 2019-10-17 21:07
@Sjoerd-van-Hagen I thought that was the agreement - We would not release the feature until the changes to the query page are reverted. And I think we need more data for releasing this feature, e.g. for all pancan studies.

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-17 22:09
@jjgao There is an option to not show the gene sets on the query page.

The pancan studies do not have expression so that would not work. We only have TCGA provisional for gbm. Let's load that and see how it works without showing them on the query page. We can then do the other TCGA provisional studies.

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-19 15:47
The pan can expression data is not yet available in cBioPortal is what I
meant.

I have spoken to our client recently and they plan to release the scripts
for computing all the scores. They are switching the algorithm from GSVA to
ssGSEA, as this has some nice properties.  After that it is simply a matter
of running the scripts against the public datasets.


--

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by schultzn** [comment] 2019-10-21 02:29
But the mRNA data are there for all PanCan Atlas studies…

**Comment by Sjoerd-van-Hagen** [comment] 2019-10-25 10:11
Hm, you are right. I must have looked at a wrong study. When were they
added?

--

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by schultzn** [comment] 2019-10-25 14:21
I thought they were their from the beginning, with the first release of the data…

**Comment by jjgao** [comment] 2019-10-25 21:42
I created two issues for the remaining gsva work.

https://github.com/cBioPortal/cbioportal/issues/6748

https://github.com/cBioPortal/datahub/issues/859

**Comment by jjgao** [comment] 2019-10-25 21:45
And another one: https://github.com/cBioPortal/cbioportal/issues/6749
