### ISSUE TITLE
mutations tab: "show all mutations" doesn't work

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/cbioportal#5253] opened 2018-11-15 16:04 UTC
If I filter the table on the mutations tab and then click "show all mutations" to remove the filter, nothing happens.

**Comment by tmazor** [comment] 2018-11-15 16:13
After testing in additional studies, this one query is the only one where this button doesn't work: http://www.cbioportal.org/results/mutations?session_id=5bed9b07e4b0776ef5b26507

**Comment by ersinciftci** [comment] 2018-11-15 16:21
And it doesn't always fail, it fails when you search for `endo` for that url, but works when you search `missense`.

**Comment by ersinciftci** [comment] 2018-11-15 19:17
Most likely duplicate of https://github.com/cBioPortal/cbioportal/issues/4549

**Closed** 2018-11-19 18:33 UTC
Labels: bug, priority, results.mutations
