### ISSUE TITLE
1.14 beta Enrichments tab: Sub-tab headers look a little big

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/cbioportal#4287] opened 2018-05-30 03:57 UTC
The Mutations / Copy-number / mRNA tab headers look bigger than most other control elements in cBioPortal:

![image](https://user-images.githubusercontent.com/11892704/40698213-f71427a2-639b-11e8-9b13-824b45022b41.png)

**Comment by ersinciftci** [comment] 2018-05-30 13:43
We can merge this issue with https://github.com/cBioPortal/cbioportal/issues/4280

**Comment by alisman** [comment] 2018-05-30 14:12
duplicate of #4280

**Closed by alisman** 2018-05-30 14:12 UTC
Labels: refactoring
