### ISSUE TITLE
Please check to see that geneset functionality works in SPA

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#4894] opened 2018-09-28 13:36 UTC

**Comment by alisman** [comment] 2018-10-04 18:16
@adamabeshouse maybe just a configuration thign?

**Comment by adamabeshouse** [comment] 2018-10-04 22:38
@oplantalech could you please deploy the latest version of `rc` to `https://cbioportal-test.thehyve.net:8081/cbioportal/` ?

**Comment by oplantalech** [comment] 2018-10-05 14:46
@adamabeshouse Done. I put the latest version of www.cbioportal.org/beta, which is not the `rc` branch, but the `spa` branch.

**Comment by alisman** [comment] 2018-10-09 18:15
@oplantalech lets discuss this tomorrow

**Comment by adamabeshouse** [comment] 2018-10-09 20:08
@oplantalech I think we really need you to deploy `rc`, our frontend isn't compatible with what you have deployed right now :/

**Comment by adamabeshouse** [comment] 2018-10-10 23:41
@oplantalech to be clear, we need the `rc` branch of https://github.com/cBioPortal/cbioportal deployed

**Comment by oplantalech** [comment] 2018-10-11 09:41
@adamabeshouse I've changed the deployed branch to `rc`.

**Comment by adamabeshouse** [comment] 2018-10-11 16:49
thanks @oplantalech

**Comment by adamabeshouse** [comment] 2018-10-11 17:59
@oplantalech I'm not able to connect to the URL, I get ERR_CONNECTION_REFUSED

**Comment by oplantalech** [comment] 2018-10-17 09:40
@adamabeshouse Can you check again? I've no problems to access: https://cbioportal-test.thehyve.net:8081/cbioportal/

**Comment by inodb** [comment] 2018-10-19 19:49
im guessing it's because of trying to load frontend over http whereas there website is served over https - shared message on slack that indicates how to serve the frontend artifacts over https

**Comment by adamabeshouse** [comment] 2018-10-19 20:20
@oplantalech gene set queries do not seem to work in oncoprint or plots. merged tracks do seem to work even when you select a geneset, but maybe thats because the geneset tracks arent actually showing up

**Comment by oplantalech** [comment] 2018-10-22 09:10
@adamabeshouse indeed, do you have any idea on what can be wrong in the geneset queries?

**Comment by pieterlukasse** [comment] 2018-10-23 08:52
apparently the selected geneset profile is not processed correctly by the query results page:

![image](https://user-images.githubusercontent.com/2900303/47348185-33b73400-d6b1-11e8-8b72-c4e3e1ae12f9.png)

although it is present in the query URL:

//cbioportal-test.thehyve.net:8081/cbioportal/results?Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=acc_tcga_test2_all&gene_list=SOX9%2520RAN%2520TNK2%2520EP300%2520PXN%2520NCOA2%2520AR%2520NRIP1%2520NCOR1%2520NCOR2&**geneset_list=ACGCACA_MIR210%20GTCGATC_MIR3695P%20SEF1_C**&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=acc_tcga_test2_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=acc_tcga_test2_gistic&**genetic_profile_ids_PROFILE_GENESET_SCORE=acc_tcga_test2_gsva_scores**&cancer_study_list=acc_tcga_test2&show_samples=false&clinicallist=PROFILED_IN_acc_tcga_test2_gistic

**Comment by jjgao** [comment] 2018-10-23 19:30
@pieterlukasse thanks! Please take a lead on this before you plan to merge 1.18 into your production.

**Comment by pieterlukasse** [comment] 2018-10-29 16:39
@adamabeshouse just discussed with @jjgao now. @oplantalech will contact you to try to fix this together using our backend at  https://cbioportal-test.thehyve.net:8081/cbioportal

I will be working with @sandertan to get GSVA data for one of the TCGA studies and work with @inodb to get this loaded in the public portal DB (while hiding it from the query page with `show_profile_in_analysis_tab: false` in gsva meta file) so we can use it to build a regression screenshot test.

**Comment by sandertan** [comment] 2018-12-06 14:42
@inodb @pieterlukasse I created test data for GSVA in this PR: https://github.com/cBioPortal/datahub/pull/492

It includes documentation on how to load the data, as well as how to use the functionality.

**Closed** 2018-12-14 16:56 UTC
Labels: frontend
